// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical
{
    [InfisicalResourceType("infisical:index/dynamicSecretAwsIam:DynamicSecretAwsIam")]
    public partial class DynamicSecretAwsIam : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The configuration of the dynamic secret
        /// </summary>
        [Output("configuration")]
        public Output<Outputs.DynamicSecretAwsIamConfiguration> Configuration { get; private set; } = null!;

        /// <summary>
        /// The default TTL that will be applied for all the leases.
        /// </summary>
        [Output("defaultTtl")]
        public Output<string> DefaultTtl { get; private set; } = null!;

        /// <summary>
        /// The slug of the environment to create the dynamic secret in.
        /// </summary>
        [Output("environmentSlug")]
        public Output<string> EnvironmentSlug { get; private set; } = null!;

        /// <summary>
        /// The maximum limit a TTL can be leases or renewed.
        /// </summary>
        [Output("maxTtl")]
        public Output<string?> MaxTtl { get; private set; } = null!;

        /// <summary>
        /// The metadata associated with this dynamic secret
        /// </summary>
        [Output("metadatas")]
        public Output<ImmutableArray<Outputs.DynamicSecretAwsIamMetadata>> Metadatas { get; private set; } = null!;

        /// <summary>
        /// The name of the dynamic secret.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The path to create the dynamic secret in.
        /// </summary>
        [Output("path")]
        public Output<string> Path { get; private set; } = null!;

        /// <summary>
        /// The slug of the project to create dynamic secret in.
        /// </summary>
        [Output("projectSlug")]
        public Output<string> ProjectSlug { get; private set; } = null!;

        /// <summary>
        /// The username template of the dynamic secret
        /// </summary>
        [Output("usernameTemplate")]
        public Output<string?> UsernameTemplate { get; private set; } = null!;


        /// <summary>
        /// Create a DynamicSecretAwsIam resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DynamicSecretAwsIam(string name, DynamicSecretAwsIamArgs args, CustomResourceOptions? options = null)
            : base("infisical:index/dynamicSecretAwsIam:DynamicSecretAwsIam", name, args ?? new DynamicSecretAwsIamArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DynamicSecretAwsIam(string name, Input<string> id, DynamicSecretAwsIamState? state = null, CustomResourceOptions? options = null)
            : base("infisical:index/dynamicSecretAwsIam:DynamicSecretAwsIam", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DynamicSecretAwsIam resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DynamicSecretAwsIam Get(string name, Input<string> id, DynamicSecretAwsIamState? state = null, CustomResourceOptions? options = null)
        {
            return new DynamicSecretAwsIam(name, id, state, options);
        }
    }

    public sealed class DynamicSecretAwsIamArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The configuration of the dynamic secret
        /// </summary>
        [Input("configuration", required: true)]
        public Input<Inputs.DynamicSecretAwsIamConfigurationArgs> Configuration { get; set; } = null!;

        /// <summary>
        /// The default TTL that will be applied for all the leases.
        /// </summary>
        [Input("defaultTtl", required: true)]
        public Input<string> DefaultTtl { get; set; } = null!;

        /// <summary>
        /// The slug of the environment to create the dynamic secret in.
        /// </summary>
        [Input("environmentSlug", required: true)]
        public Input<string> EnvironmentSlug { get; set; } = null!;

        /// <summary>
        /// The maximum limit a TTL can be leases or renewed.
        /// </summary>
        [Input("maxTtl")]
        public Input<string>? MaxTtl { get; set; }

        [Input("metadatas")]
        private InputList<Inputs.DynamicSecretAwsIamMetadataArgs>? _metadatas;

        /// <summary>
        /// The metadata associated with this dynamic secret
        /// </summary>
        public InputList<Inputs.DynamicSecretAwsIamMetadataArgs> Metadatas
        {
            get => _metadatas ?? (_metadatas = new InputList<Inputs.DynamicSecretAwsIamMetadataArgs>());
            set => _metadatas = value;
        }

        /// <summary>
        /// The name of the dynamic secret.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The path to create the dynamic secret in.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        /// <summary>
        /// The slug of the project to create dynamic secret in.
        /// </summary>
        [Input("projectSlug", required: true)]
        public Input<string> ProjectSlug { get; set; } = null!;

        /// <summary>
        /// The username template of the dynamic secret
        /// </summary>
        [Input("usernameTemplate")]
        public Input<string>? UsernameTemplate { get; set; }

        public DynamicSecretAwsIamArgs()
        {
        }
        public static new DynamicSecretAwsIamArgs Empty => new DynamicSecretAwsIamArgs();
    }

    public sealed class DynamicSecretAwsIamState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The configuration of the dynamic secret
        /// </summary>
        [Input("configuration")]
        public Input<Inputs.DynamicSecretAwsIamConfigurationGetArgs>? Configuration { get; set; }

        /// <summary>
        /// The default TTL that will be applied for all the leases.
        /// </summary>
        [Input("defaultTtl")]
        public Input<string>? DefaultTtl { get; set; }

        /// <summary>
        /// The slug of the environment to create the dynamic secret in.
        /// </summary>
        [Input("environmentSlug")]
        public Input<string>? EnvironmentSlug { get; set; }

        /// <summary>
        /// The maximum limit a TTL can be leases or renewed.
        /// </summary>
        [Input("maxTtl")]
        public Input<string>? MaxTtl { get; set; }

        [Input("metadatas")]
        private InputList<Inputs.DynamicSecretAwsIamMetadataGetArgs>? _metadatas;

        /// <summary>
        /// The metadata associated with this dynamic secret
        /// </summary>
        public InputList<Inputs.DynamicSecretAwsIamMetadataGetArgs> Metadatas
        {
            get => _metadatas ?? (_metadatas = new InputList<Inputs.DynamicSecretAwsIamMetadataGetArgs>());
            set => _metadatas = value;
        }

        /// <summary>
        /// The name of the dynamic secret.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The path to create the dynamic secret in.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// The slug of the project to create dynamic secret in.
        /// </summary>
        [Input("projectSlug")]
        public Input<string>? ProjectSlug { get; set; }

        /// <summary>
        /// The username template of the dynamic secret
        /// </summary>
        [Input("usernameTemplate")]
        public Input<string>? UsernameTemplate { get; set; }

        public DynamicSecretAwsIamState()
        {
        }
        public static new DynamicSecretAwsIamState Empty => new DynamicSecretAwsIamState();
    }
}
