// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package infisical

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sapslaj/pulumi-infisical/sdk/go/infisical/internal"
)

func GetSecretFolders(ctx *pulumi.Context, args *GetSecretFoldersArgs, opts ...pulumi.InvokeOption) (*GetSecretFoldersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSecretFoldersResult
	err := ctx.Invoke("infisical:index/getSecretFolders:getSecretFolders", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSecretFolders.
type GetSecretFoldersArgs struct {
	EnvironmentSlug string `pulumi:"environmentSlug"`
	FolderPath      string `pulumi:"folderPath"`
	ProjectId       string `pulumi:"projectId"`
}

// A collection of values returned by getSecretFolders.
type GetSecretFoldersResult struct {
	EnvironmentSlug string                   `pulumi:"environmentSlug"`
	FolderPath      string                   `pulumi:"folderPath"`
	Folders         []GetSecretFoldersFolder `pulumi:"folders"`
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	ProjectId string `pulumi:"projectId"`
}

func GetSecretFoldersOutput(ctx *pulumi.Context, args GetSecretFoldersOutputArgs, opts ...pulumi.InvokeOption) GetSecretFoldersResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSecretFoldersResultOutput, error) {
			args := v.(GetSecretFoldersArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("infisical:index/getSecretFolders:getSecretFolders", args, GetSecretFoldersResultOutput{}, options).(GetSecretFoldersResultOutput), nil
		}).(GetSecretFoldersResultOutput)
}

// A collection of arguments for invoking getSecretFolders.
type GetSecretFoldersOutputArgs struct {
	EnvironmentSlug pulumi.StringInput `pulumi:"environmentSlug"`
	FolderPath      pulumi.StringInput `pulumi:"folderPath"`
	ProjectId       pulumi.StringInput `pulumi:"projectId"`
}

func (GetSecretFoldersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSecretFoldersArgs)(nil)).Elem()
}

// A collection of values returned by getSecretFolders.
type GetSecretFoldersResultOutput struct{ *pulumi.OutputState }

func (GetSecretFoldersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSecretFoldersResult)(nil)).Elem()
}

func (o GetSecretFoldersResultOutput) ToGetSecretFoldersResultOutput() GetSecretFoldersResultOutput {
	return o
}

func (o GetSecretFoldersResultOutput) ToGetSecretFoldersResultOutputWithContext(ctx context.Context) GetSecretFoldersResultOutput {
	return o
}

func (o GetSecretFoldersResultOutput) EnvironmentSlug() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretFoldersResult) string { return v.EnvironmentSlug }).(pulumi.StringOutput)
}

func (o GetSecretFoldersResultOutput) FolderPath() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretFoldersResult) string { return v.FolderPath }).(pulumi.StringOutput)
}

func (o GetSecretFoldersResultOutput) Folders() GetSecretFoldersFolderArrayOutput {
	return o.ApplyT(func(v GetSecretFoldersResult) []GetSecretFoldersFolder { return v.Folders }).(GetSecretFoldersFolderArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetSecretFoldersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretFoldersResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSecretFoldersResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretFoldersResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSecretFoldersResultOutput{})
}
