// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package infisical

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sapslaj/pulumi-infisical/sdk/go/infisical/internal"
)

func LookupSecretTag(ctx *pulumi.Context, args *LookupSecretTagArgs, opts ...pulumi.InvokeOption) (*LookupSecretTagResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSecretTagResult
	err := ctx.Invoke("infisical:index/getSecretTag:getSecretTag", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSecretTag.
type LookupSecretTagArgs struct {
	ProjectId string `pulumi:"projectId"`
	Slug      string `pulumi:"slug"`
}

// A collection of values returned by getSecretTag.
type LookupSecretTagResult struct {
	Color     string `pulumi:"color"`
	Id        string `pulumi:"id"`
	Name      string `pulumi:"name"`
	ProjectId string `pulumi:"projectId"`
	Slug      string `pulumi:"slug"`
}

func LookupSecretTagOutput(ctx *pulumi.Context, args LookupSecretTagOutputArgs, opts ...pulumi.InvokeOption) LookupSecretTagResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSecretTagResultOutput, error) {
			args := v.(LookupSecretTagArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("infisical:index/getSecretTag:getSecretTag", args, LookupSecretTagResultOutput{}, options).(LookupSecretTagResultOutput), nil
		}).(LookupSecretTagResultOutput)
}

// A collection of arguments for invoking getSecretTag.
type LookupSecretTagOutputArgs struct {
	ProjectId pulumi.StringInput `pulumi:"projectId"`
	Slug      pulumi.StringInput `pulumi:"slug"`
}

func (LookupSecretTagOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecretTagArgs)(nil)).Elem()
}

// A collection of values returned by getSecretTag.
type LookupSecretTagResultOutput struct{ *pulumi.OutputState }

func (LookupSecretTagResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecretTagResult)(nil)).Elem()
}

func (o LookupSecretTagResultOutput) ToLookupSecretTagResultOutput() LookupSecretTagResultOutput {
	return o
}

func (o LookupSecretTagResultOutput) ToLookupSecretTagResultOutputWithContext(ctx context.Context) LookupSecretTagResultOutput {
	return o
}

func (o LookupSecretTagResultOutput) Color() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecretTagResult) string { return v.Color }).(pulumi.StringOutput)
}

func (o LookupSecretTagResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecretTagResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSecretTagResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecretTagResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSecretTagResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecretTagResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

func (o LookupSecretTagResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecretTagResult) string { return v.Slug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSecretTagResultOutput{})
}
