// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package infisical

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sapslaj/pulumi-infisical/sdk/go/infisical/internal"
)

func GetSecrets(ctx *pulumi.Context, args *GetSecretsArgs, opts ...pulumi.InvokeOption) (*GetSecretsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSecretsResult
	err := ctx.Invoke("infisical:index/getSecrets:getSecrets", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSecrets.
type GetSecretsArgs struct {
	EnvSlug     string  `pulumi:"envSlug"`
	FolderPath  string  `pulumi:"folderPath"`
	WorkspaceId *string `pulumi:"workspaceId"`
}

// A collection of values returned by getSecrets.
type GetSecretsResult struct {
	EnvSlug    string `pulumi:"envSlug"`
	FolderPath string `pulumi:"folderPath"`
	// The provider-assigned unique ID for this managed resource.
	Id          string                       `pulumi:"id"`
	Secrets     map[string]GetSecretsSecrets `pulumi:"secrets"`
	WorkspaceId string                       `pulumi:"workspaceId"`
}

func GetSecretsOutput(ctx *pulumi.Context, args GetSecretsOutputArgs, opts ...pulumi.InvokeOption) GetSecretsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSecretsResultOutput, error) {
			args := v.(GetSecretsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("infisical:index/getSecrets:getSecrets", args, GetSecretsResultOutput{}, options).(GetSecretsResultOutput), nil
		}).(GetSecretsResultOutput)
}

// A collection of arguments for invoking getSecrets.
type GetSecretsOutputArgs struct {
	EnvSlug     pulumi.StringInput    `pulumi:"envSlug"`
	FolderPath  pulumi.StringInput    `pulumi:"folderPath"`
	WorkspaceId pulumi.StringPtrInput `pulumi:"workspaceId"`
}

func (GetSecretsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSecretsArgs)(nil)).Elem()
}

// A collection of values returned by getSecrets.
type GetSecretsResultOutput struct{ *pulumi.OutputState }

func (GetSecretsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSecretsResult)(nil)).Elem()
}

func (o GetSecretsResultOutput) ToGetSecretsResultOutput() GetSecretsResultOutput {
	return o
}

func (o GetSecretsResultOutput) ToGetSecretsResultOutputWithContext(ctx context.Context) GetSecretsResultOutput {
	return o
}

func (o GetSecretsResultOutput) EnvSlug() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretsResult) string { return v.EnvSlug }).(pulumi.StringOutput)
}

func (o GetSecretsResultOutput) FolderPath() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretsResult) string { return v.FolderPath }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetSecretsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSecretsResultOutput) Secrets() GetSecretsSecretsMapOutput {
	return o.ApplyT(func(v GetSecretsResult) map[string]GetSecretsSecrets { return v.Secrets }).(GetSecretsSecretsMapOutput)
}

func (o GetSecretsResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretsResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSecretsResultOutput{})
}
