// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class AppConnectionAzureClientSecretsCredentials
    {
        /// <summary>
        /// The Azure application (client) ID. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// The Azure client secret. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
        /// </summary>
        public readonly string ClientSecret;
        /// <summary>
        /// The Azure Active Directory (AAD) tenant ID. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
        /// </summary>
        public readonly string TenantId;

        [OutputConstructor]
        private AppConnectionAzureClientSecretsCredentials(
            string clientId,

            string clientSecret,

            string tenantId)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            TenantId = tenantId;
        }
    }
}
