// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class AppConnectionPostgresCredentials
    {
        /// <summary>
        /// The name of the database to connect to.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// The hostname of the database server.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// The password to connect to the database with.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// The port number of the database.
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// The SSL certificate to use for connection.
        /// </summary>
        public readonly string? SslCertificate;
        /// <summary>
        /// Whether or not to use SSL when connecting to the database.
        /// </summary>
        public readonly bool? SslEnabled;
        /// <summary>
        /// Whether or not to reject unauthorized SSL certificates.
        /// </summary>
        public readonly bool? SslRejectUnauthorized;
        /// <summary>
        /// The username to connect to the database with.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private AppConnectionPostgresCredentials(
            string database,

            string host,

            string password,

            int? port,

            string? sslCertificate,

            bool? sslEnabled,

            bool? sslRejectUnauthorized,

            string username)
        {
            Database = database;
            Host = host;
            Password = password;
            Port = port;
            SslCertificate = sslCertificate;
            SslEnabled = sslEnabled;
            SslRejectUnauthorized = sslRejectUnauthorized;
            Username = username;
        }
    }
}
