// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class DynamicSecretSqlDatabaseConfigurationPasswordRequirementsRequired
    {
        /// <summary>
        /// The number of digits required in the password.
        /// </summary>
        public readonly int Digits;
        /// <summary>
        /// The number of lowercase characters required in the password.
        /// </summary>
        public readonly int Lowercase;
        /// <summary>
        /// The number of symbols required in the password.
        /// </summary>
        public readonly int Symbols;
        /// <summary>
        /// The number of uppercase characters required in the password.
        /// </summary>
        public readonly int Uppercase;

        [OutputConstructor]
        private DynamicSecretSqlDatabaseConfigurationPasswordRequirementsRequired(
            int digits,

            int lowercase,

            int symbols,

            int uppercase)
        {
            Digits = digits;
            Lowercase = lowercase;
            Symbols = symbols;
            Uppercase = uppercase;
        }
    }
}
