// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class ProjectRolePermissionConditions
    {
        /// <summary>
        /// The environment slug this permission should allow.
        /// </summary>
        public readonly string? Environment;
        /// <summary>
        /// The secret path this permission should be scoped to
        /// </summary>
        public readonly string? SecretPath;

        [OutputConstructor]
        private ProjectRolePermissionConditions(
            string? environment,

            string? secretPath)
        {
            Environment = environment;
            SecretPath = secretPath;
        }
    }
}
