// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class ProjectGroupRole
    {
        /// <summary>
        /// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
        /// </summary>
        public readonly bool? IsTemporary;
        /// <summary>
        /// The slug of the role
        /// </summary>
        public readonly string RoleSlug;
        /// <summary>
        /// ISO time for which temporary access should begin. This is in the format YYYY-MM-DDTHH:MM:SSZ e.g. 2024-09-19T12:43:13Z
        /// </summary>
        public readonly string? TemporaryAccessStartTime;
        /// <summary>
        /// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
        /// </summary>
        public readonly string? TemporaryRange;

        [OutputConstructor]
        private ProjectGroupRole(
            bool? isTemporary,

            string roleSlug,

            string? temporaryAccessStartTime,

            string? temporaryRange)
        {
            IsTemporary = isTemporary;
            RoleSlug = roleSlug;
            TemporaryAccessStartTime = temporaryAccessStartTime;
            TemporaryRange = temporaryRange;
        }
    }
}
