// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class ProjectTemplateRole
    {
        /// <summary>
        /// The name of the role
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The permissions assigned to the role. Refer to the documentation here https://infisical.com/docs/api-reference/endpoints/project-templates/create#body-roles-permissions for its usage.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectTemplateRolePermission> Permissions;
        /// <summary>
        /// The slug of the role
        /// </summary>
        public readonly string Slug;

        [OutputConstructor]
        private ProjectTemplateRole(
            string name,

            ImmutableArray<Outputs.ProjectTemplateRolePermission> permissions,

            string slug)
        {
            Name = name;
            Permissions = permissions;
            Slug = slug;
        }
    }
}
