// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class SecretSyncDatabricksDestinationConfig
    {
        /// <summary>
        /// The Databricks secret scope to sync secrets to.
        /// </summary>
        public readonly string Scope;

        [OutputConstructor]
        private SecretSyncDatabricksDestinationConfig(string scope)
        {
            Scope = scope;
        }
    }
}
