// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class SecretSyncBitbucketDestinationConfig
    {
        /// <summary>
        /// The Bitbucket deployment environment ID (optional).
        /// </summary>
        public readonly string? EnvironmentId;
        /// <summary>
        /// The Bitbucket repository slug to sync secrets to.
        /// </summary>
        public readonly string RepositorySlug;
        /// <summary>
        /// The Bitbucket workspace slug.
        /// </summary>
        public readonly string WorkspaceSlug;

        [OutputConstructor]
        private SecretSyncBitbucketDestinationConfig(
            string? environmentId,

            string repositorySlug,

            string workspaceSlug)
        {
            EnvironmentId = environmentId;
            RepositorySlug = repositorySlug;
            WorkspaceSlug = workspaceSlug;
        }
    }
}
