// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class SecretSyncAwsSecretsManagerDestinationConfig
    {
        /// <summary>
        /// The AWS region of your AWS Secrets Manager
        /// </summary>
        public readonly string AwsRegion;
        /// <summary>
        /// The name of the AWS secret to map to. This only applies when mapping_behavior is set to 'many-to-one'.
        /// </summary>
        public readonly string? AwsSecretsManagerSecretName;
        /// <summary>
        /// The behavior of the mapping. Can be 'many-to-one' or 'one-to-one'. Many to One: All Infisical secrets will be mapped to a single AWS secret. One to One: Each Infisical secret will be mapped to its own AWS secret.
        /// </summary>
        public readonly string? MappingBehavior;

        [OutputConstructor]
        private SecretSyncAwsSecretsManagerDestinationConfig(
            string awsRegion,

            string? awsSecretsManagerSecretName,

            string? mappingBehavior)
        {
            AwsRegion = awsRegion;
            AwsSecretsManagerSecretName = awsSecretsManagerSecretName;
            MappingBehavior = mappingBehavior;
        }
    }
}
