// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Outputs
{

    [OutputType]
    public sealed class SecretSyncGcpSecretManagerDestinationConfig
    {
        /// <summary>
        /// The ID of the GCP project to sync with
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// The scope of the sync with GCP Secret Manager. Supported options: global
        /// </summary>
        public readonly string? Scope;

        [OutputConstructor]
        private SecretSyncGcpSecretManagerDestinationConfig(
            string projectId,

            string? scope)
        {
            ProjectId = projectId;
            Scope = scope;
        }
    }
}
