// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/sapslaj/pulumi-infisical/sdk/go/infisical/internal"
)

var _ = internal.GetEnvOrDefault

// The configuration values for authentication
func GetAuth(ctx *pulumi.Context) string {
	return config.Get(ctx, "infisical:auth")
}

// (DEPRECATED, Use the `auth` attribute), Machine identity client ID. Used to fetch/modify secrets for a given project.
func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "infisical:clientId")
}

// (DEPRECATED, use `auth` attribute), Machine identity client secret. Used to fetch/modify secrets for a given project
func GetClientSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "infisical:clientSecret")
}

// Used to point the client to fetch secrets from your self hosted instance of Infisical. If not host is provided, https://app.infisical.com is the default host. This attribute can also be set using the `INFISICAL_HOST` environment variable
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "infisical:host")
}

// (DEPRECATED, Use machine identity auth), Used to fetch/modify secrets for a given project
func GetServiceToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "infisical:serviceToken")
}
