// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AppConnectionDatadog extends pulumi.CustomResource {
    /**
     * Get an existing AppConnectionDatadog resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AppConnectionDatadogState, opts?: pulumi.CustomResourceOptions): AppConnectionDatadog {
        return new AppConnectionDatadog(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/appConnectionDatadog:AppConnectionDatadog';

    /**
     * Returns true if the given object is an instance of AppConnectionDatadog.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AppConnectionDatadog {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AppConnectionDatadog.__pulumiType;
    }

    /**
     * The credentials for the Datadog App Connection
     */
    declare public readonly credentials: pulumi.Output<outputs.AppConnectionDatadogCredentials>;
    /**
     * The hash of the Datadog App Connection credentials
     */
    declare public /*out*/ readonly credentialsHash: pulumi.Output<string>;
    /**
     * An optional description for the Datadog App Connection.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The method used to authenticate with Datadog. Possible values are: api-key
     */
    declare public readonly method: pulumi.Output<string>;
    /**
     * The name of the Datadog App Connection to create. Must be slug-friendly
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
     */
    declare public readonly projectId: pulumi.Output<string | undefined>;

    /**
     * Create a AppConnectionDatadog resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AppConnectionDatadogArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AppConnectionDatadogArgs | AppConnectionDatadogState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AppConnectionDatadogState | undefined;
            resourceInputs["credentials"] = state?.credentials;
            resourceInputs["credentialsHash"] = state?.credentialsHash;
            resourceInputs["description"] = state?.description;
            resourceInputs["method"] = state?.method;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
        } else {
            const args = argsOrState as AppConnectionDatadogArgs | undefined;
            if (args?.credentials === undefined && !opts.urn) {
                throw new Error("Missing required property 'credentials'");
            }
            if (args?.method === undefined && !opts.urn) {
                throw new Error("Missing required property 'method'");
            }
            resourceInputs["credentials"] = args?.credentials;
            resourceInputs["description"] = args?.description;
            resourceInputs["method"] = args?.method;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["credentialsHash"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AppConnectionDatadog.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AppConnectionDatadog resources.
 */
export interface AppConnectionDatadogState {
    /**
     * The credentials for the Datadog App Connection
     */
    credentials?: pulumi.Input<inputs.AppConnectionDatadogCredentials | undefined>;
    /**
     * The hash of the Datadog App Connection credentials
     */
    credentialsHash?: pulumi.Input<string | undefined>;
    /**
     * An optional description for the Datadog App Connection.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The method used to authenticate with Datadog. Possible values are: api-key
     */
    method?: pulumi.Input<string | undefined>;
    /**
     * The name of the Datadog App Connection to create. Must be slug-friendly
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
     */
    projectId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AppConnectionDatadog resource.
 */
export interface AppConnectionDatadogArgs {
    /**
     * The credentials for the Datadog App Connection
     */
    credentials: pulumi.Input<inputs.AppConnectionDatadogCredentials>;
    /**
     * An optional description for the Datadog App Connection.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The method used to authenticate with Datadog. Possible values are: api-key
     */
    method: pulumi.Input<string>;
    /**
     * The name of the Datadog App Connection to create. Must be slug-friendly
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
     */
    projectId?: pulumi.Input<string | undefined>;
}
