// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CertManagerApplicationGroup extends pulumi.CustomResource {
    /**
     * Get an existing CertManagerApplicationGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CertManagerApplicationGroupState, opts?: pulumi.CustomResourceOptions): CertManagerApplicationGroup {
        return new CertManagerApplicationGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/certManagerApplicationGroup:CertManagerApplicationGroup';

    /**
     * Returns true if the given object is an instance of CertManagerApplicationGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CertManagerApplicationGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CertManagerApplicationGroup.__pulumiType;
    }

    /**
     * The ID of the Certificate Manager application
     */
    declare public readonly applicationId: pulumi.Output<string>;
    /**
     * The ID of the group to add
     */
    declare public readonly groupId: pulumi.Output<string>;
    /**
     * The role to assign to the group (admin, operator, or auditor)
     */
    declare public readonly role: pulumi.Output<string>;

    /**
     * Create a CertManagerApplicationGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CertManagerApplicationGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CertManagerApplicationGroupArgs | CertManagerApplicationGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CertManagerApplicationGroupState | undefined;
            resourceInputs["applicationId"] = state?.applicationId;
            resourceInputs["groupId"] = state?.groupId;
            resourceInputs["role"] = state?.role;
        } else {
            const args = argsOrState as CertManagerApplicationGroupArgs | undefined;
            if (args?.applicationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'applicationId'");
            }
            if (args?.groupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'groupId'");
            }
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["applicationId"] = args?.applicationId;
            resourceInputs["groupId"] = args?.groupId;
            resourceInputs["role"] = args?.role;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CertManagerApplicationGroup.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CertManagerApplicationGroup resources.
 */
export interface CertManagerApplicationGroupState {
    /**
     * The ID of the Certificate Manager application
     */
    applicationId?: pulumi.Input<string | undefined>;
    /**
     * The ID of the group to add
     */
    groupId?: pulumi.Input<string | undefined>;
    /**
     * The role to assign to the group (admin, operator, or auditor)
     */
    role?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a CertManagerApplicationGroup resource.
 */
export interface CertManagerApplicationGroupArgs {
    /**
     * The ID of the Certificate Manager application
     */
    applicationId: pulumi.Input<string>;
    /**
     * The ID of the group to add
     */
    groupId: pulumi.Input<string>;
    /**
     * The role to assign to the group (admin, operator, or auditor)
     */
    role: pulumi.Input<string>;
}
