// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Gateway extends pulumi.CustomResource {
    /**
     * Get an existing Gateway resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayState, opts?: pulumi.CustomResourceOptions): Gateway {
        return new Gateway(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/gateway:Gateway';

    /**
     * Returns true if the given object is an instance of Gateway.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Gateway {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Gateway.__pulumiType;
    }

    /**
     * Authenticate the gateway with its AWS IAM identity. The machine re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedPrincipalArns`" pulumi-lang-dotnet="`AllowedPrincipalArns`" pulumi-lang-go="`allowedPrincipalArns`" pulumi-lang-python="`allowed_principal_arns`" pulumi-lang-yaml="`allowedPrincipalArns`" pulumi-lang-java="`allowedPrincipalArns`" pulumi-lang-hcl="`allowed_principal_arns`">`allowedPrincipalArns`</span> or <span pulumi-lang-nodejs="`allowedAccountIds`" pulumi-lang-dotnet="`AllowedAccountIds`" pulumi-lang-go="`allowedAccountIds`" pulumi-lang-python="`allowed_account_ids`" pulumi-lang-yaml="`allowedAccountIds`" pulumi-lang-java="`allowedAccountIds`" pulumi-lang-hcl="`allowed_account_ids`">`allowedAccountIds`</span> must be non-empty.
     */
    declare public readonly awsAuth: pulumi.Output<outputs.GatewayAwsAuth | undefined>;
    /**
     * Authenticate the gateway with its GCP identity. The machine re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedServiceAccounts`" pulumi-lang-dotnet="`AllowedServiceAccounts`" pulumi-lang-go="`allowedServiceAccounts`" pulumi-lang-python="`allowed_service_accounts`" pulumi-lang-yaml="`allowedServiceAccounts`" pulumi-lang-java="`allowedServiceAccounts`" pulumi-lang-hcl="`allowed_service_accounts`">`allowedServiceAccounts`</span> or <span pulumi-lang-nodejs="`allowedProjects`" pulumi-lang-dotnet="`AllowedProjects`" pulumi-lang-go="`allowedProjects`" pulumi-lang-python="`allowed_projects`" pulumi-lang-yaml="`allowedProjects`" pulumi-lang-java="`allowedProjects`" pulumi-lang-hcl="`allowed_projects`">`allowedProjects`</span> must be non-empty.
     */
    declare public readonly gcpAuth: pulumi.Output<outputs.GatewayGcpAuth | undefined>;
    /**
     * Authenticate the gateway with its Kubernetes service account token. The pod re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedNamespaces`" pulumi-lang-dotnet="`AllowedNamespaces`" pulumi-lang-go="`allowedNamespaces`" pulumi-lang-python="`allowed_namespaces`" pulumi-lang-yaml="`allowedNamespaces`" pulumi-lang-java="`allowedNamespaces`" pulumi-lang-hcl="`allowed_namespaces`">`allowedNamespaces`</span> or <span pulumi-lang-nodejs="`allowedServiceAccountNames`" pulumi-lang-dotnet="`AllowedServiceAccountNames`" pulumi-lang-go="`allowedServiceAccountNames`" pulumi-lang-python="`allowed_service_account_names`" pulumi-lang-yaml="`allowedServiceAccountNames`" pulumi-lang-java="`allowedServiceAccountNames`" pulumi-lang-hcl="`allowed_service_account_names`">`allowedServiceAccountNames`</span> must be non-empty.
     */
    declare public readonly kubernetesAuth: pulumi.Output<outputs.GatewayKubernetesAuth | undefined>;
    /**
     * The name of the gateway. Unique within the organization. Renaming is an in-place update, so the gateway keeps its ID and anything referencing it keeps working.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Authenticate the gateway with a one-time enrollment token. The token itself is minted by a separate <span pulumi-lang-nodejs="`infisical.GatewayEnrollmentToken`" pulumi-lang-dotnet="`infisical.GatewayEnrollmentToken`" pulumi-lang-go="`GatewayEnrollmentToken`" pulumi-lang-python="`GatewayEnrollmentToken`" pulumi-lang-yaml="`infisical.GatewayEnrollmentToken`" pulumi-lang-java="`infisical.GatewayEnrollmentToken`" pulumi-lang-hcl="`infisical_gateway_enrollment_token`">`infisical.GatewayEnrollmentToken`</span> resource. This block takes no arguments, because token auth has nothing to configure: write <span pulumi-lang-nodejs="`tokenAuth " pulumi-lang-dotnet="`TokenAuth " pulumi-lang-go="`tokenAuth " pulumi-lang-python="`token_auth " pulumi-lang-yaml="`tokenAuth " pulumi-lang-java="`tokenAuth " pulumi-lang-hcl="`token_auth ">`tokenAuth </span>= {}`. Prefer <span pulumi-lang-nodejs="`awsAuth`" pulumi-lang-dotnet="`AwsAuth`" pulumi-lang-go="`awsAuth`" pulumi-lang-python="`aws_auth`" pulumi-lang-yaml="`awsAuth`" pulumi-lang-java="`awsAuth`" pulumi-lang-hcl="`aws_auth`">`awsAuth`</span>, <span pulumi-lang-nodejs="`gcpAuth`" pulumi-lang-dotnet="`GcpAuth`" pulumi-lang-go="`gcpAuth`" pulumi-lang-python="`gcp_auth`" pulumi-lang-yaml="`gcpAuth`" pulumi-lang-java="`gcpAuth`" pulumi-lang-hcl="`gcp_auth`">`gcpAuth`</span> or <span pulumi-lang-nodejs="`kubernetesAuth`" pulumi-lang-dotnet="`KubernetesAuth`" pulumi-lang-go="`kubernetesAuth`" pulumi-lang-python="`kubernetes_auth`" pulumi-lang-yaml="`kubernetesAuth`" pulumi-lang-java="`kubernetesAuth`" pulumi-lang-hcl="`kubernetes_auth`">`kubernetesAuth`</span> where the platform can vouch for the machine, since those re-authenticate on every start and put no secret in state.
     */
    declare public readonly tokenAuth: pulumi.Output<outputs.GatewayTokenAuth | undefined>;

    /**
     * Create a Gateway resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GatewayArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayArgs | GatewayState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayState | undefined;
            resourceInputs["awsAuth"] = state?.awsAuth;
            resourceInputs["gcpAuth"] = state?.gcpAuth;
            resourceInputs["kubernetesAuth"] = state?.kubernetesAuth;
            resourceInputs["name"] = state?.name;
            resourceInputs["tokenAuth"] = state?.tokenAuth;
        } else {
            const args = argsOrState as GatewayArgs | undefined;
            resourceInputs["awsAuth"] = args?.awsAuth;
            resourceInputs["gcpAuth"] = args?.gcpAuth;
            resourceInputs["kubernetesAuth"] = args?.kubernetesAuth;
            resourceInputs["name"] = args?.name;
            resourceInputs["tokenAuth"] = args?.tokenAuth;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Gateway.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Gateway resources.
 */
export interface GatewayState {
    /**
     * Authenticate the gateway with its AWS IAM identity. The machine re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedPrincipalArns`" pulumi-lang-dotnet="`AllowedPrincipalArns`" pulumi-lang-go="`allowedPrincipalArns`" pulumi-lang-python="`allowed_principal_arns`" pulumi-lang-yaml="`allowedPrincipalArns`" pulumi-lang-java="`allowedPrincipalArns`" pulumi-lang-hcl="`allowed_principal_arns`">`allowedPrincipalArns`</span> or <span pulumi-lang-nodejs="`allowedAccountIds`" pulumi-lang-dotnet="`AllowedAccountIds`" pulumi-lang-go="`allowedAccountIds`" pulumi-lang-python="`allowed_account_ids`" pulumi-lang-yaml="`allowedAccountIds`" pulumi-lang-java="`allowedAccountIds`" pulumi-lang-hcl="`allowed_account_ids`">`allowedAccountIds`</span> must be non-empty.
     */
    awsAuth?: pulumi.Input<inputs.GatewayAwsAuth | undefined>;
    /**
     * Authenticate the gateway with its GCP identity. The machine re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedServiceAccounts`" pulumi-lang-dotnet="`AllowedServiceAccounts`" pulumi-lang-go="`allowedServiceAccounts`" pulumi-lang-python="`allowed_service_accounts`" pulumi-lang-yaml="`allowedServiceAccounts`" pulumi-lang-java="`allowedServiceAccounts`" pulumi-lang-hcl="`allowed_service_accounts`">`allowedServiceAccounts`</span> or <span pulumi-lang-nodejs="`allowedProjects`" pulumi-lang-dotnet="`AllowedProjects`" pulumi-lang-go="`allowedProjects`" pulumi-lang-python="`allowed_projects`" pulumi-lang-yaml="`allowedProjects`" pulumi-lang-java="`allowedProjects`" pulumi-lang-hcl="`allowed_projects`">`allowedProjects`</span> must be non-empty.
     */
    gcpAuth?: pulumi.Input<inputs.GatewayGcpAuth | undefined>;
    /**
     * Authenticate the gateway with its Kubernetes service account token. The pod re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedNamespaces`" pulumi-lang-dotnet="`AllowedNamespaces`" pulumi-lang-go="`allowedNamespaces`" pulumi-lang-python="`allowed_namespaces`" pulumi-lang-yaml="`allowedNamespaces`" pulumi-lang-java="`allowedNamespaces`" pulumi-lang-hcl="`allowed_namespaces`">`allowedNamespaces`</span> or <span pulumi-lang-nodejs="`allowedServiceAccountNames`" pulumi-lang-dotnet="`AllowedServiceAccountNames`" pulumi-lang-go="`allowedServiceAccountNames`" pulumi-lang-python="`allowed_service_account_names`" pulumi-lang-yaml="`allowedServiceAccountNames`" pulumi-lang-java="`allowedServiceAccountNames`" pulumi-lang-hcl="`allowed_service_account_names`">`allowedServiceAccountNames`</span> must be non-empty.
     */
    kubernetesAuth?: pulumi.Input<inputs.GatewayKubernetesAuth | undefined>;
    /**
     * The name of the gateway. Unique within the organization. Renaming is an in-place update, so the gateway keeps its ID and anything referencing it keeps working.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Authenticate the gateway with a one-time enrollment token. The token itself is minted by a separate <span pulumi-lang-nodejs="`infisical.GatewayEnrollmentToken`" pulumi-lang-dotnet="`infisical.GatewayEnrollmentToken`" pulumi-lang-go="`GatewayEnrollmentToken`" pulumi-lang-python="`GatewayEnrollmentToken`" pulumi-lang-yaml="`infisical.GatewayEnrollmentToken`" pulumi-lang-java="`infisical.GatewayEnrollmentToken`" pulumi-lang-hcl="`infisical_gateway_enrollment_token`">`infisical.GatewayEnrollmentToken`</span> resource. This block takes no arguments, because token auth has nothing to configure: write <span pulumi-lang-nodejs="`tokenAuth " pulumi-lang-dotnet="`TokenAuth " pulumi-lang-go="`tokenAuth " pulumi-lang-python="`token_auth " pulumi-lang-yaml="`tokenAuth " pulumi-lang-java="`tokenAuth " pulumi-lang-hcl="`token_auth ">`tokenAuth </span>= {}`. Prefer <span pulumi-lang-nodejs="`awsAuth`" pulumi-lang-dotnet="`AwsAuth`" pulumi-lang-go="`awsAuth`" pulumi-lang-python="`aws_auth`" pulumi-lang-yaml="`awsAuth`" pulumi-lang-java="`awsAuth`" pulumi-lang-hcl="`aws_auth`">`awsAuth`</span>, <span pulumi-lang-nodejs="`gcpAuth`" pulumi-lang-dotnet="`GcpAuth`" pulumi-lang-go="`gcpAuth`" pulumi-lang-python="`gcp_auth`" pulumi-lang-yaml="`gcpAuth`" pulumi-lang-java="`gcpAuth`" pulumi-lang-hcl="`gcp_auth`">`gcpAuth`</span> or <span pulumi-lang-nodejs="`kubernetesAuth`" pulumi-lang-dotnet="`KubernetesAuth`" pulumi-lang-go="`kubernetesAuth`" pulumi-lang-python="`kubernetes_auth`" pulumi-lang-yaml="`kubernetesAuth`" pulumi-lang-java="`kubernetesAuth`" pulumi-lang-hcl="`kubernetes_auth`">`kubernetesAuth`</span> where the platform can vouch for the machine, since those re-authenticate on every start and put no secret in state.
     */
    tokenAuth?: pulumi.Input<inputs.GatewayTokenAuth | undefined>;
}

/**
 * The set of arguments for constructing a Gateway resource.
 */
export interface GatewayArgs {
    /**
     * Authenticate the gateway with its AWS IAM identity. The machine re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedPrincipalArns`" pulumi-lang-dotnet="`AllowedPrincipalArns`" pulumi-lang-go="`allowedPrincipalArns`" pulumi-lang-python="`allowed_principal_arns`" pulumi-lang-yaml="`allowedPrincipalArns`" pulumi-lang-java="`allowedPrincipalArns`" pulumi-lang-hcl="`allowed_principal_arns`">`allowedPrincipalArns`</span> or <span pulumi-lang-nodejs="`allowedAccountIds`" pulumi-lang-dotnet="`AllowedAccountIds`" pulumi-lang-go="`allowedAccountIds`" pulumi-lang-python="`allowed_account_ids`" pulumi-lang-yaml="`allowedAccountIds`" pulumi-lang-java="`allowedAccountIds`" pulumi-lang-hcl="`allowed_account_ids`">`allowedAccountIds`</span> must be non-empty.
     */
    awsAuth?: pulumi.Input<inputs.GatewayAwsAuth | undefined>;
    /**
     * Authenticate the gateway with its GCP identity. The machine re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedServiceAccounts`" pulumi-lang-dotnet="`AllowedServiceAccounts`" pulumi-lang-go="`allowedServiceAccounts`" pulumi-lang-python="`allowed_service_accounts`" pulumi-lang-yaml="`allowedServiceAccounts`" pulumi-lang-java="`allowedServiceAccounts`" pulumi-lang-hcl="`allowed_service_accounts`">`allowedServiceAccounts`</span> or <span pulumi-lang-nodejs="`allowedProjects`" pulumi-lang-dotnet="`AllowedProjects`" pulumi-lang-go="`allowedProjects`" pulumi-lang-python="`allowed_projects`" pulumi-lang-yaml="`allowedProjects`" pulumi-lang-java="`allowedProjects`" pulumi-lang-hcl="`allowed_projects`">`allowedProjects`</span> must be non-empty.
     */
    gcpAuth?: pulumi.Input<inputs.GatewayGcpAuth | undefined>;
    /**
     * Authenticate the gateway with its Kubernetes service account token. The pod re-authenticates on every start, so no secret is stored. At least one of <span pulumi-lang-nodejs="`allowedNamespaces`" pulumi-lang-dotnet="`AllowedNamespaces`" pulumi-lang-go="`allowedNamespaces`" pulumi-lang-python="`allowed_namespaces`" pulumi-lang-yaml="`allowedNamespaces`" pulumi-lang-java="`allowedNamespaces`" pulumi-lang-hcl="`allowed_namespaces`">`allowedNamespaces`</span> or <span pulumi-lang-nodejs="`allowedServiceAccountNames`" pulumi-lang-dotnet="`AllowedServiceAccountNames`" pulumi-lang-go="`allowedServiceAccountNames`" pulumi-lang-python="`allowed_service_account_names`" pulumi-lang-yaml="`allowedServiceAccountNames`" pulumi-lang-java="`allowedServiceAccountNames`" pulumi-lang-hcl="`allowed_service_account_names`">`allowedServiceAccountNames`</span> must be non-empty.
     */
    kubernetesAuth?: pulumi.Input<inputs.GatewayKubernetesAuth | undefined>;
    /**
     * The name of the gateway. Unique within the organization. Renaming is an in-place update, so the gateway keeps its ID and anything referencing it keeps working.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Authenticate the gateway with a one-time enrollment token. The token itself is minted by a separate <span pulumi-lang-nodejs="`infisical.GatewayEnrollmentToken`" pulumi-lang-dotnet="`infisical.GatewayEnrollmentToken`" pulumi-lang-go="`GatewayEnrollmentToken`" pulumi-lang-python="`GatewayEnrollmentToken`" pulumi-lang-yaml="`infisical.GatewayEnrollmentToken`" pulumi-lang-java="`infisical.GatewayEnrollmentToken`" pulumi-lang-hcl="`infisical_gateway_enrollment_token`">`infisical.GatewayEnrollmentToken`</span> resource. This block takes no arguments, because token auth has nothing to configure: write <span pulumi-lang-nodejs="`tokenAuth " pulumi-lang-dotnet="`TokenAuth " pulumi-lang-go="`tokenAuth " pulumi-lang-python="`token_auth " pulumi-lang-yaml="`tokenAuth " pulumi-lang-java="`tokenAuth " pulumi-lang-hcl="`token_auth ">`tokenAuth </span>= {}`. Prefer <span pulumi-lang-nodejs="`awsAuth`" pulumi-lang-dotnet="`AwsAuth`" pulumi-lang-go="`awsAuth`" pulumi-lang-python="`aws_auth`" pulumi-lang-yaml="`awsAuth`" pulumi-lang-java="`awsAuth`" pulumi-lang-hcl="`aws_auth`">`awsAuth`</span>, <span pulumi-lang-nodejs="`gcpAuth`" pulumi-lang-dotnet="`GcpAuth`" pulumi-lang-go="`gcpAuth`" pulumi-lang-python="`gcp_auth`" pulumi-lang-yaml="`gcpAuth`" pulumi-lang-java="`gcpAuth`" pulumi-lang-hcl="`gcp_auth`">`gcpAuth`</span> or <span pulumi-lang-nodejs="`kubernetesAuth`" pulumi-lang-dotnet="`KubernetesAuth`" pulumi-lang-go="`kubernetesAuth`" pulumi-lang-python="`kubernetes_auth`" pulumi-lang-yaml="`kubernetesAuth`" pulumi-lang-java="`kubernetesAuth`" pulumi-lang-hcl="`kubernetes_auth`">`kubernetesAuth`</span> where the platform can vouch for the machine, since those re-authenticate on every start and put no secret in state.
     */
    tokenAuth?: pulumi.Input<inputs.GatewayTokenAuth | undefined>;
}
