// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getIdentityOidcAuthTemplate(args?: GetIdentityOidcAuthTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetIdentityOidcAuthTemplateResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("infisical:index/getIdentityOidcAuthTemplate:getIdentityOidcAuthTemplate", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIdentityOidcAuthTemplate.
 */
export interface GetIdentityOidcAuthTemplateArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getIdentityOidcAuthTemplate.
 */
export interface GetIdentityOidcAuthTemplateResult {
    readonly boundAudiences: string[];
    readonly boundIssuer: string;
    readonly id: string;
    readonly name: string;
    readonly oidcCaCertificate: string;
    readonly oidcDiscoveryUrl: string;
}
export function getIdentityOidcAuthTemplateOutput(args?: GetIdentityOidcAuthTemplateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIdentityOidcAuthTemplateResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("infisical:index/getIdentityOidcAuthTemplate:getIdentityOidcAuthTemplate", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIdentityOidcAuthTemplate.
 */
export interface GetIdentityOidcAuthTemplateOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
