// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getProjectUsersList(args: GetProjectUsersListArgs, opts?: pulumi.InvokeOptions): Promise<GetProjectUsersListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("infisical:index/getProjectUsersList:getProjectUsersList", {
        "projectId": args.projectId,
        "usernames": args.usernames,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getProjectUsersList.
 */
export interface GetProjectUsersListArgs {
    projectId: string;
    usernames?: string[];
}

/**
 * A collection of values returned by getProjectUsersList.
 */
export interface GetProjectUsersListResult {
    readonly members: outputs.GetProjectUsersListMember[];
    readonly projectId: string;
    readonly usernames?: string[];
}
export function getProjectUsersListOutput(args: GetProjectUsersListOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetProjectUsersListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("infisical:index/getProjectUsersList:getProjectUsersList", {
        "projectId": args.projectId,
        "usernames": args.usernames,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getProjectUsersList.
 */
export interface GetProjectUsersListOutputArgs {
    projectId: pulumi.Input<string>;
    usernames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
