// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSecretValidationRules(args: GetSecretValidationRulesArgs, opts?: pulumi.InvokeOptions): Promise<GetSecretValidationRulesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("infisical:index/getSecretValidationRules:getSecretValidationRules", {
        "projectId": args.projectId,
        "type": args.type,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSecretValidationRules.
 */
export interface GetSecretValidationRulesArgs {
    projectId: string;
    type?: string;
}

/**
 * A collection of values returned by getSecretValidationRules.
 */
export interface GetSecretValidationRulesResult {
    readonly projectId: string;
    readonly rules: outputs.GetSecretValidationRulesRule[];
    readonly type?: string;
}
export function getSecretValidationRulesOutput(args: GetSecretValidationRulesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecretValidationRulesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("infisical:index/getSecretValidationRules:getSecretValidationRules", {
        "projectId": args.projectId,
        "type": args.type,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSecretValidationRules.
 */
export interface GetSecretValidationRulesOutputArgs {
    projectId: pulumi.Input<string>;
    type?: pulumi.Input<string | undefined>;
}
