// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IdentityJwtAuth extends pulumi.CustomResource {
    /**
     * Get an existing IdentityJwtAuth resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityJwtAuthState, opts?: pulumi.CustomResourceOptions): IdentityJwtAuth {
        return new IdentityJwtAuth(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/identityJwtAuth:IdentityJwtAuth';

    /**
     * Returns true if the given object is an instance of IdentityJwtAuth.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdentityJwtAuth {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityJwtAuth.__pulumiType;
    }

    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    declare public readonly accessTokenMaxTtl: pulumi.Output<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default: 0
     */
    declare public readonly accessTokenNumUsesLimit: pulumi.Output<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address.
     */
    declare public readonly accessTokenTrustedIps: pulumi.Output<outputs.IdentityJwtAuthAccessTokenTrustedIp[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    declare public readonly accessTokenTtl: pulumi.Output<number>;
    /**
     * The list of intended recipients.
     */
    declare public readonly boundAudiences: pulumi.Output<string[]>;
    /**
     * The attributes that should be present in the JWT for it to be valid.
     */
    declare public readonly boundClaims: pulumi.Output<{[key: string]: string}>;
    /**
     * The unique identifier of the identity provider issuing the JWTs.
     */
    declare public readonly boundIssuer: pulumi.Output<string>;
    /**
     * The expected principal that is the subject of the JWT.
     */
    declare public readonly boundSubject: pulumi.Output<string>;
    /**
     * The configuration type of the JWT auth. Must be 'jwks' or 'static'.
     */
    declare public readonly configurationType: pulumi.Output<string>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    declare public readonly identityId: pulumi.Output<string>;
    /**
     * The PEM-encoded CA certificate for validating the TLS connection to the JWKS URL.
     */
    declare public readonly jwksCaCert: pulumi.Output<string>;
    /**
     * The URL used to retrieve the JSON Web Key Set (JWKS) for verifying JWTs. Required when<span pulumi-lang-nodejs=" configurationType " pulumi-lang-dotnet=" ConfigurationType " pulumi-lang-go=" configurationType " pulumi-lang-python=" configuration_type " pulumi-lang-yaml=" configurationType " pulumi-lang-java=" configurationType "> configuration_type </span>is 'jwks'.
     */
    declare public readonly jwksUrl: pulumi.Output<string>;
    /**
     * A list of PEM-encoded public keys used to verify JWTs. Required when<span pulumi-lang-nodejs=" configurationType " pulumi-lang-dotnet=" ConfigurationType " pulumi-lang-go=" configurationType " pulumi-lang-python=" configuration_type " pulumi-lang-yaml=" configurationType " pulumi-lang-java=" configurationType "> configuration_type </span>is 'static'.
     */
    declare public readonly publicKeys: pulumi.Output<string[]>;

    /**
     * Create a IdentityJwtAuth resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityJwtAuthArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityJwtAuthArgs | IdentityJwtAuthState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdentityJwtAuthState | undefined;
            resourceInputs["accessTokenMaxTtl"] = state?.accessTokenMaxTtl;
            resourceInputs["accessTokenNumUsesLimit"] = state?.accessTokenNumUsesLimit;
            resourceInputs["accessTokenTrustedIps"] = state?.accessTokenTrustedIps;
            resourceInputs["accessTokenTtl"] = state?.accessTokenTtl;
            resourceInputs["boundAudiences"] = state?.boundAudiences;
            resourceInputs["boundClaims"] = state?.boundClaims;
            resourceInputs["boundIssuer"] = state?.boundIssuer;
            resourceInputs["boundSubject"] = state?.boundSubject;
            resourceInputs["configurationType"] = state?.configurationType;
            resourceInputs["identityId"] = state?.identityId;
            resourceInputs["jwksCaCert"] = state?.jwksCaCert;
            resourceInputs["jwksUrl"] = state?.jwksUrl;
            resourceInputs["publicKeys"] = state?.publicKeys;
        } else {
            const args = argsOrState as IdentityJwtAuthArgs | undefined;
            if (args?.configurationType === undefined && !opts.urn) {
                throw new Error("Missing required property 'configurationType'");
            }
            if (args?.identityId === undefined && !opts.urn) {
                throw new Error("Missing required property 'identityId'");
            }
            resourceInputs["accessTokenMaxTtl"] = args?.accessTokenMaxTtl;
            resourceInputs["accessTokenNumUsesLimit"] = args?.accessTokenNumUsesLimit;
            resourceInputs["accessTokenTrustedIps"] = args?.accessTokenTrustedIps;
            resourceInputs["accessTokenTtl"] = args?.accessTokenTtl;
            resourceInputs["boundAudiences"] = args?.boundAudiences;
            resourceInputs["boundClaims"] = args?.boundClaims;
            resourceInputs["boundIssuer"] = args?.boundIssuer;
            resourceInputs["boundSubject"] = args?.boundSubject;
            resourceInputs["configurationType"] = args?.configurationType;
            resourceInputs["identityId"] = args?.identityId;
            resourceInputs["jwksCaCert"] = args?.jwksCaCert;
            resourceInputs["jwksUrl"] = args?.jwksUrl;
            resourceInputs["publicKeys"] = args?.publicKeys;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IdentityJwtAuth.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IdentityJwtAuth resources.
 */
export interface IdentityJwtAuthState {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default: 0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address.
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityJwtAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * The list of intended recipients.
     */
    boundAudiences?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The attributes that should be present in the JWT for it to be valid.
     */
    boundClaims?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The unique identifier of the identity provider issuing the JWTs.
     */
    boundIssuer?: pulumi.Input<string>;
    /**
     * The expected principal that is the subject of the JWT.
     */
    boundSubject?: pulumi.Input<string>;
    /**
     * The configuration type of the JWT auth. Must be 'jwks' or 'static'.
     */
    configurationType?: pulumi.Input<string>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId?: pulumi.Input<string>;
    /**
     * The PEM-encoded CA certificate for validating the TLS connection to the JWKS URL.
     */
    jwksCaCert?: pulumi.Input<string>;
    /**
     * The URL used to retrieve the JSON Web Key Set (JWKS) for verifying JWTs. Required when<span pulumi-lang-nodejs=" configurationType " pulumi-lang-dotnet=" ConfigurationType " pulumi-lang-go=" configurationType " pulumi-lang-python=" configuration_type " pulumi-lang-yaml=" configurationType " pulumi-lang-java=" configurationType "> configuration_type </span>is 'jwks'.
     */
    jwksUrl?: pulumi.Input<string>;
    /**
     * A list of PEM-encoded public keys used to verify JWTs. Required when<span pulumi-lang-nodejs=" configurationType " pulumi-lang-dotnet=" ConfigurationType " pulumi-lang-go=" configurationType " pulumi-lang-python=" configuration_type " pulumi-lang-yaml=" configurationType " pulumi-lang-java=" configurationType "> configuration_type </span>is 'static'.
     */
    publicKeys?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a IdentityJwtAuth resource.
 */
export interface IdentityJwtAuthArgs {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default: 0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address.
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityJwtAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * The list of intended recipients.
     */
    boundAudiences?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The attributes that should be present in the JWT for it to be valid.
     */
    boundClaims?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The unique identifier of the identity provider issuing the JWTs.
     */
    boundIssuer?: pulumi.Input<string>;
    /**
     * The expected principal that is the subject of the JWT.
     */
    boundSubject?: pulumi.Input<string>;
    /**
     * The configuration type of the JWT auth. Must be 'jwks' or 'static'.
     */
    configurationType: pulumi.Input<string>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId: pulumi.Input<string>;
    /**
     * The PEM-encoded CA certificate for validating the TLS connection to the JWKS URL.
     */
    jwksCaCert?: pulumi.Input<string>;
    /**
     * The URL used to retrieve the JSON Web Key Set (JWKS) for verifying JWTs. Required when<span pulumi-lang-nodejs=" configurationType " pulumi-lang-dotnet=" ConfigurationType " pulumi-lang-go=" configurationType " pulumi-lang-python=" configuration_type " pulumi-lang-yaml=" configurationType " pulumi-lang-java=" configurationType "> configuration_type </span>is 'jwks'.
     */
    jwksUrl?: pulumi.Input<string>;
    /**
     * A list of PEM-encoded public keys used to verify JWTs. Required when<span pulumi-lang-nodejs=" configurationType " pulumi-lang-dotnet=" ConfigurationType " pulumi-lang-go=" configurationType " pulumi-lang-python=" configuration_type " pulumi-lang-yaml=" configurationType " pulumi-lang-java=" configurationType "> configuration_type </span>is 'static'.
     */
    publicKeys?: pulumi.Input<pulumi.Input<string>[]>;
}
