// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IdentityTokenAuth extends pulumi.CustomResource {
    /**
     * Get an existing IdentityTokenAuth resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityTokenAuthState, opts?: pulumi.CustomResourceOptions): IdentityTokenAuth {
        return new IdentityTokenAuth(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/identityTokenAuth:IdentityTokenAuth';

    /**
     * Returns true if the given object is an instance of IdentityTokenAuth.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdentityTokenAuth {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityTokenAuth.__pulumiType;
    }

    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    declare public readonly accessTokenMaxTtl: pulumi.Output<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    declare public readonly accessTokenNumUsesLimit: pulumi.Output<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address...
     */
    declare public readonly accessTokenTrustedIps: pulumi.Output<outputs.IdentityTokenAuthAccessTokenTrustedIp[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    declare public readonly accessTokenTtl: pulumi.Output<number>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    declare public readonly identityId: pulumi.Output<string>;

    /**
     * Create a IdentityTokenAuth resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityTokenAuthArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityTokenAuthArgs | IdentityTokenAuthState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdentityTokenAuthState | undefined;
            resourceInputs["accessTokenMaxTtl"] = state?.accessTokenMaxTtl;
            resourceInputs["accessTokenNumUsesLimit"] = state?.accessTokenNumUsesLimit;
            resourceInputs["accessTokenTrustedIps"] = state?.accessTokenTrustedIps;
            resourceInputs["accessTokenTtl"] = state?.accessTokenTtl;
            resourceInputs["identityId"] = state?.identityId;
        } else {
            const args = argsOrState as IdentityTokenAuthArgs | undefined;
            if (args?.identityId === undefined && !opts.urn) {
                throw new Error("Missing required property 'identityId'");
            }
            resourceInputs["accessTokenMaxTtl"] = args?.accessTokenMaxTtl;
            resourceInputs["accessTokenNumUsesLimit"] = args?.accessTokenNumUsesLimit;
            resourceInputs["accessTokenTrustedIps"] = args?.accessTokenTrustedIps;
            resourceInputs["accessTokenTtl"] = args?.accessTokenTtl;
            resourceInputs["identityId"] = args?.identityId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IdentityTokenAuth.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IdentityTokenAuth resources.
 */
export interface IdentityTokenAuthState {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address...
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityTokenAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IdentityTokenAuth resource.
 */
export interface IdentityTokenAuthArgs {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address...
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityTokenAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId: pulumi.Input<string>;
}
