// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IdentityTokenAuthToken extends pulumi.CustomResource {
    /**
     * Get an existing IdentityTokenAuthToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityTokenAuthTokenState, opts?: pulumi.CustomResourceOptions): IdentityTokenAuthToken {
        return new IdentityTokenAuthToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/identityTokenAuthToken:IdentityTokenAuthToken';

    /**
     * Returns true if the given object is an instance of IdentityTokenAuthToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdentityTokenAuthToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityTokenAuthToken.__pulumiType;
    }

    /**
     * The UTC timestamp of the created at date.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The ID of the identity to create a token for
     */
    declare public readonly identityId: pulumi.Output<string>;
    /**
     * A flag indicating token has been revoked
     */
    declare public /*out*/ readonly isRevoked: pulumi.Output<boolean>;
    /**
     * The name of the token auth token
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The number of times that the token is used
     */
    declare public /*out*/ readonly numberOfUses: pulumi.Output<number>;
    /**
     * The maximum number of times that the token can be used; a value of 0 implies infinite number of uses. Default: 0
     */
    declare public /*out*/ readonly numberOfUsesLimit: pulumi.Output<number>;
    /**
     * The token.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * The lifetime for the token in seconds. Default: 0 - not expiring
     */
    declare public /*out*/ readonly ttl: pulumi.Output<number>;

    /**
     * Create a IdentityTokenAuthToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityTokenAuthTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityTokenAuthTokenArgs | IdentityTokenAuthTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdentityTokenAuthTokenState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["identityId"] = state?.identityId;
            resourceInputs["isRevoked"] = state?.isRevoked;
            resourceInputs["name"] = state?.name;
            resourceInputs["numberOfUses"] = state?.numberOfUses;
            resourceInputs["numberOfUsesLimit"] = state?.numberOfUsesLimit;
            resourceInputs["token"] = state?.token;
            resourceInputs["ttl"] = state?.ttl;
        } else {
            const args = argsOrState as IdentityTokenAuthTokenArgs | undefined;
            if (args?.identityId === undefined && !opts.urn) {
                throw new Error("Missing required property 'identityId'");
            }
            resourceInputs["identityId"] = args?.identityId;
            resourceInputs["name"] = args?.name;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["isRevoked"] = undefined /*out*/;
            resourceInputs["numberOfUses"] = undefined /*out*/;
            resourceInputs["numberOfUsesLimit"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["ttl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IdentityTokenAuthToken.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IdentityTokenAuthToken resources.
 */
export interface IdentityTokenAuthTokenState {
    /**
     * The UTC timestamp of the created at date.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * The ID of the identity to create a token for
     */
    identityId?: pulumi.Input<string>;
    /**
     * A flag indicating token has been revoked
     */
    isRevoked?: pulumi.Input<boolean>;
    /**
     * The name of the token auth token
     */
    name?: pulumi.Input<string>;
    /**
     * The number of times that the token is used
     */
    numberOfUses?: pulumi.Input<number>;
    /**
     * The maximum number of times that the token can be used; a value of 0 implies infinite number of uses. Default: 0
     */
    numberOfUsesLimit?: pulumi.Input<number>;
    /**
     * The token.
     */
    token?: pulumi.Input<string>;
    /**
     * The lifetime for the token in seconds. Default: 0 - not expiring
     */
    ttl?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a IdentityTokenAuthToken resource.
 */
export interface IdentityTokenAuthTokenArgs {
    /**
     * The ID of the identity to create a token for
     */
    identityId: pulumi.Input<string>;
    /**
     * The name of the token auth token
     */
    name?: pulumi.Input<string>;
}
