// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AccessApprovalPolicyArgs, AccessApprovalPolicyState } from "./accessApprovalPolicy";
export type AccessApprovalPolicy = import("./accessApprovalPolicy").AccessApprovalPolicy;
export const AccessApprovalPolicy: typeof import("./accessApprovalPolicy").AccessApprovalPolicy = null as any;
utilities.lazyLoad(exports, ["AccessApprovalPolicy"], () => require("./accessApprovalPolicy"));

export { AppConnection1passwordArgs, AppConnection1passwordState } from "./appConnection1password";
export type AppConnection1password = import("./appConnection1password").AppConnection1password;
export const AppConnection1password: typeof import("./appConnection1password").AppConnection1password = null as any;
utilities.lazyLoad(exports, ["AppConnection1password"], () => require("./appConnection1password"));

export { AppConnectionAwsArgs, AppConnectionAwsState } from "./appConnectionAws";
export type AppConnectionAws = import("./appConnectionAws").AppConnectionAws;
export const AppConnectionAws: typeof import("./appConnectionAws").AppConnectionAws = null as any;
utilities.lazyLoad(exports, ["AppConnectionAws"], () => require("./appConnectionAws"));

export { AppConnectionAzureClientSecretsArgs, AppConnectionAzureClientSecretsState } from "./appConnectionAzureClientSecrets";
export type AppConnectionAzureClientSecrets = import("./appConnectionAzureClientSecrets").AppConnectionAzureClientSecrets;
export const AppConnectionAzureClientSecrets: typeof import("./appConnectionAzureClientSecrets").AppConnectionAzureClientSecrets = null as any;
utilities.lazyLoad(exports, ["AppConnectionAzureClientSecrets"], () => require("./appConnectionAzureClientSecrets"));

export { AppConnectionBitbucketArgs, AppConnectionBitbucketState } from "./appConnectionBitbucket";
export type AppConnectionBitbucket = import("./appConnectionBitbucket").AppConnectionBitbucket;
export const AppConnectionBitbucket: typeof import("./appConnectionBitbucket").AppConnectionBitbucket = null as any;
utilities.lazyLoad(exports, ["AppConnectionBitbucket"], () => require("./appConnectionBitbucket"));

export { AppConnectionCloudflareArgs, AppConnectionCloudflareState } from "./appConnectionCloudflare";
export type AppConnectionCloudflare = import("./appConnectionCloudflare").AppConnectionCloudflare;
export const AppConnectionCloudflare: typeof import("./appConnectionCloudflare").AppConnectionCloudflare = null as any;
utilities.lazyLoad(exports, ["AppConnectionCloudflare"], () => require("./appConnectionCloudflare"));

export { AppConnectionDatabricksArgs, AppConnectionDatabricksState } from "./appConnectionDatabricks";
export type AppConnectionDatabricks = import("./appConnectionDatabricks").AppConnectionDatabricks;
export const AppConnectionDatabricks: typeof import("./appConnectionDatabricks").AppConnectionDatabricks = null as any;
utilities.lazyLoad(exports, ["AppConnectionDatabricks"], () => require("./appConnectionDatabricks"));

export { AppConnectionFlyioArgs, AppConnectionFlyioState } from "./appConnectionFlyio";
export type AppConnectionFlyio = import("./appConnectionFlyio").AppConnectionFlyio;
export const AppConnectionFlyio: typeof import("./appConnectionFlyio").AppConnectionFlyio = null as any;
utilities.lazyLoad(exports, ["AppConnectionFlyio"], () => require("./appConnectionFlyio"));

export { AppConnectionGcpArgs, AppConnectionGcpState } from "./appConnectionGcp";
export type AppConnectionGcp = import("./appConnectionGcp").AppConnectionGcp;
export const AppConnectionGcp: typeof import("./appConnectionGcp").AppConnectionGcp = null as any;
utilities.lazyLoad(exports, ["AppConnectionGcp"], () => require("./appConnectionGcp"));

export { AppConnectionGitlabArgs, AppConnectionGitlabState } from "./appConnectionGitlab";
export type AppConnectionGitlab = import("./appConnectionGitlab").AppConnectionGitlab;
export const AppConnectionGitlab: typeof import("./appConnectionGitlab").AppConnectionGitlab = null as any;
utilities.lazyLoad(exports, ["AppConnectionGitlab"], () => require("./appConnectionGitlab"));

export { AppConnectionLdapArgs, AppConnectionLdapState } from "./appConnectionLdap";
export type AppConnectionLdap = import("./appConnectionLdap").AppConnectionLdap;
export const AppConnectionLdap: typeof import("./appConnectionLdap").AppConnectionLdap = null as any;
utilities.lazyLoad(exports, ["AppConnectionLdap"], () => require("./appConnectionLdap"));

export { AppConnectionMssqlArgs, AppConnectionMssqlState } from "./appConnectionMssql";
export type AppConnectionMssql = import("./appConnectionMssql").AppConnectionMssql;
export const AppConnectionMssql: typeof import("./appConnectionMssql").AppConnectionMssql = null as any;
utilities.lazyLoad(exports, ["AppConnectionMssql"], () => require("./appConnectionMssql"));

export { AppConnectionMysqlArgs, AppConnectionMysqlState } from "./appConnectionMysql";
export type AppConnectionMysql = import("./appConnectionMysql").AppConnectionMysql;
export const AppConnectionMysql: typeof import("./appConnectionMysql").AppConnectionMysql = null as any;
utilities.lazyLoad(exports, ["AppConnectionMysql"], () => require("./appConnectionMysql"));

export { AppConnectionOracledbArgs, AppConnectionOracledbState } from "./appConnectionOracledb";
export type AppConnectionOracledb = import("./appConnectionOracledb").AppConnectionOracledb;
export const AppConnectionOracledb: typeof import("./appConnectionOracledb").AppConnectionOracledb = null as any;
utilities.lazyLoad(exports, ["AppConnectionOracledb"], () => require("./appConnectionOracledb"));

export { AppConnectionPostgresArgs, AppConnectionPostgresState } from "./appConnectionPostgres";
export type AppConnectionPostgres = import("./appConnectionPostgres").AppConnectionPostgres;
export const AppConnectionPostgres: typeof import("./appConnectionPostgres").AppConnectionPostgres = null as any;
utilities.lazyLoad(exports, ["AppConnectionPostgres"], () => require("./appConnectionPostgres"));

export { AppConnectionRenderArgs, AppConnectionRenderState } from "./appConnectionRender";
export type AppConnectionRender = import("./appConnectionRender").AppConnectionRender;
export const AppConnectionRender: typeof import("./appConnectionRender").AppConnectionRender = null as any;
utilities.lazyLoad(exports, ["AppConnectionRender"], () => require("./appConnectionRender"));

export { AppConnectionSupabaseArgs, AppConnectionSupabaseState } from "./appConnectionSupabase";
export type AppConnectionSupabase = import("./appConnectionSupabase").AppConnectionSupabase;
export const AppConnectionSupabase: typeof import("./appConnectionSupabase").AppConnectionSupabase = null as any;
utilities.lazyLoad(exports, ["AppConnectionSupabase"], () => require("./appConnectionSupabase"));

export { DynamicSecretAwsIamArgs, DynamicSecretAwsIamState } from "./dynamicSecretAwsIam";
export type DynamicSecretAwsIam = import("./dynamicSecretAwsIam").DynamicSecretAwsIam;
export const DynamicSecretAwsIam: typeof import("./dynamicSecretAwsIam").DynamicSecretAwsIam = null as any;
utilities.lazyLoad(exports, ["DynamicSecretAwsIam"], () => require("./dynamicSecretAwsIam"));

export { DynamicSecretKubernetesArgs, DynamicSecretKubernetesState } from "./dynamicSecretKubernetes";
export type DynamicSecretKubernetes = import("./dynamicSecretKubernetes").DynamicSecretKubernetes;
export const DynamicSecretKubernetes: typeof import("./dynamicSecretKubernetes").DynamicSecretKubernetes = null as any;
utilities.lazyLoad(exports, ["DynamicSecretKubernetes"], () => require("./dynamicSecretKubernetes"));

export { DynamicSecretSqlDatabaseArgs, DynamicSecretSqlDatabaseState } from "./dynamicSecretSqlDatabase";
export type DynamicSecretSqlDatabase = import("./dynamicSecretSqlDatabase").DynamicSecretSqlDatabase;
export const DynamicSecretSqlDatabase: typeof import("./dynamicSecretSqlDatabase").DynamicSecretSqlDatabase = null as any;
utilities.lazyLoad(exports, ["DynamicSecretSqlDatabase"], () => require("./dynamicSecretSqlDatabase"));

export { GetGroupsResult } from "./getGroups";
export const getGroups: typeof import("./getGroups").getGroups = null as any;
export const getGroupsOutput: typeof import("./getGroups").getGroupsOutput = null as any;
utilities.lazyLoad(exports, ["getGroups","getGroupsOutput"], () => require("./getGroups"));

export { GetIdentityDetailsResult } from "./getIdentityDetails";
export const getIdentityDetails: typeof import("./getIdentityDetails").getIdentityDetails = null as any;
export const getIdentityDetailsOutput: typeof import("./getIdentityDetails").getIdentityDetailsOutput = null as any;
utilities.lazyLoad(exports, ["getIdentityDetails","getIdentityDetailsOutput"], () => require("./getIdentityDetails"));

export { GetProjectsArgs, GetProjectsResult, GetProjectsOutputArgs } from "./getProjects";
export const getProjects: typeof import("./getProjects").getProjects = null as any;
export const getProjectsOutput: typeof import("./getProjects").getProjectsOutput = null as any;
utilities.lazyLoad(exports, ["getProjects","getProjectsOutput"], () => require("./getProjects"));

export { GetSecretFoldersArgs, GetSecretFoldersResult, GetSecretFoldersOutputArgs } from "./getSecretFolders";
export const getSecretFolders: typeof import("./getSecretFolders").getSecretFolders = null as any;
export const getSecretFoldersOutput: typeof import("./getSecretFolders").getSecretFoldersOutput = null as any;
utilities.lazyLoad(exports, ["getSecretFolders","getSecretFoldersOutput"], () => require("./getSecretFolders"));

export { GetSecretTagArgs, GetSecretTagResult, GetSecretTagOutputArgs } from "./getSecretTag";
export const getSecretTag: typeof import("./getSecretTag").getSecretTag = null as any;
export const getSecretTagOutput: typeof import("./getSecretTag").getSecretTagOutput = null as any;
utilities.lazyLoad(exports, ["getSecretTag","getSecretTagOutput"], () => require("./getSecretTag"));

export { GetSecretsArgs, GetSecretsResult, GetSecretsOutputArgs } from "./getSecrets";
export const getSecrets: typeof import("./getSecrets").getSecrets = null as any;
export const getSecretsOutput: typeof import("./getSecrets").getSecretsOutput = null as any;
utilities.lazyLoad(exports, ["getSecrets","getSecretsOutput"], () => require("./getSecrets"));

export { GroupArgs, GroupState } from "./group";
export type Group = import("./group").Group;
export const Group: typeof import("./group").Group = null as any;
utilities.lazyLoad(exports, ["Group"], () => require("./group"));

export { IdentityArgs, IdentityState } from "./identity";
export type Identity = import("./identity").Identity;
export const Identity: typeof import("./identity").Identity = null as any;
utilities.lazyLoad(exports, ["Identity"], () => require("./identity"));

export { IdentityAwsAuthArgs, IdentityAwsAuthState } from "./identityAwsAuth";
export type IdentityAwsAuth = import("./identityAwsAuth").IdentityAwsAuth;
export const IdentityAwsAuth: typeof import("./identityAwsAuth").IdentityAwsAuth = null as any;
utilities.lazyLoad(exports, ["IdentityAwsAuth"], () => require("./identityAwsAuth"));

export { IdentityAzureAuthArgs, IdentityAzureAuthState } from "./identityAzureAuth";
export type IdentityAzureAuth = import("./identityAzureAuth").IdentityAzureAuth;
export const IdentityAzureAuth: typeof import("./identityAzureAuth").IdentityAzureAuth = null as any;
utilities.lazyLoad(exports, ["IdentityAzureAuth"], () => require("./identityAzureAuth"));

export { IdentityGcpAuthArgs, IdentityGcpAuthState } from "./identityGcpAuth";
export type IdentityGcpAuth = import("./identityGcpAuth").IdentityGcpAuth;
export const IdentityGcpAuth: typeof import("./identityGcpAuth").IdentityGcpAuth = null as any;
utilities.lazyLoad(exports, ["IdentityGcpAuth"], () => require("./identityGcpAuth"));

export { IdentityKubernetesAuthArgs, IdentityKubernetesAuthState } from "./identityKubernetesAuth";
export type IdentityKubernetesAuth = import("./identityKubernetesAuth").IdentityKubernetesAuth;
export const IdentityKubernetesAuth: typeof import("./identityKubernetesAuth").IdentityKubernetesAuth = null as any;
utilities.lazyLoad(exports, ["IdentityKubernetesAuth"], () => require("./identityKubernetesAuth"));

export { IdentityOidcAuthArgs, IdentityOidcAuthState } from "./identityOidcAuth";
export type IdentityOidcAuth = import("./identityOidcAuth").IdentityOidcAuth;
export const IdentityOidcAuth: typeof import("./identityOidcAuth").IdentityOidcAuth = null as any;
utilities.lazyLoad(exports, ["IdentityOidcAuth"], () => require("./identityOidcAuth"));

export { IdentityUniversalAuthArgs, IdentityUniversalAuthState } from "./identityUniversalAuth";
export type IdentityUniversalAuth = import("./identityUniversalAuth").IdentityUniversalAuth;
export const IdentityUniversalAuth: typeof import("./identityUniversalAuth").IdentityUniversalAuth = null as any;
utilities.lazyLoad(exports, ["IdentityUniversalAuth"], () => require("./identityUniversalAuth"));

export { IdentityUniversalAuthClientSecretArgs, IdentityUniversalAuthClientSecretState } from "./identityUniversalAuthClientSecret";
export type IdentityUniversalAuthClientSecret = import("./identityUniversalAuthClientSecret").IdentityUniversalAuthClientSecret;
export const IdentityUniversalAuthClientSecret: typeof import("./identityUniversalAuthClientSecret").IdentityUniversalAuthClientSecret = null as any;
utilities.lazyLoad(exports, ["IdentityUniversalAuthClientSecret"], () => require("./identityUniversalAuthClientSecret"));

export { IntegrationAwsParameterStoreArgs, IntegrationAwsParameterStoreState } from "./integrationAwsParameterStore";
export type IntegrationAwsParameterStore = import("./integrationAwsParameterStore").IntegrationAwsParameterStore;
export const IntegrationAwsParameterStore: typeof import("./integrationAwsParameterStore").IntegrationAwsParameterStore = null as any;
utilities.lazyLoad(exports, ["IntegrationAwsParameterStore"], () => require("./integrationAwsParameterStore"));

export { IntegrationAwsSecretsManagerArgs, IntegrationAwsSecretsManagerState } from "./integrationAwsSecretsManager";
export type IntegrationAwsSecretsManager = import("./integrationAwsSecretsManager").IntegrationAwsSecretsManager;
export const IntegrationAwsSecretsManager: typeof import("./integrationAwsSecretsManager").IntegrationAwsSecretsManager = null as any;
utilities.lazyLoad(exports, ["IntegrationAwsSecretsManager"], () => require("./integrationAwsSecretsManager"));

export { IntegrationCircleciArgs, IntegrationCircleciState } from "./integrationCircleci";
export type IntegrationCircleci = import("./integrationCircleci").IntegrationCircleci;
export const IntegrationCircleci: typeof import("./integrationCircleci").IntegrationCircleci = null as any;
utilities.lazyLoad(exports, ["IntegrationCircleci"], () => require("./integrationCircleci"));

export { IntegrationDatabricksArgs, IntegrationDatabricksState } from "./integrationDatabricks";
export type IntegrationDatabricks = import("./integrationDatabricks").IntegrationDatabricks;
export const IntegrationDatabricks: typeof import("./integrationDatabricks").IntegrationDatabricks = null as any;
utilities.lazyLoad(exports, ["IntegrationDatabricks"], () => require("./integrationDatabricks"));

export { IntegrationGcpSecretManagerArgs, IntegrationGcpSecretManagerState } from "./integrationGcpSecretManager";
export type IntegrationGcpSecretManager = import("./integrationGcpSecretManager").IntegrationGcpSecretManager;
export const IntegrationGcpSecretManager: typeof import("./integrationGcpSecretManager").IntegrationGcpSecretManager = null as any;
utilities.lazyLoad(exports, ["IntegrationGcpSecretManager"], () => require("./integrationGcpSecretManager"));

export { ProjectArgs, ProjectState } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export { ProjectEnvironmentArgs, ProjectEnvironmentState } from "./projectEnvironment";
export type ProjectEnvironment = import("./projectEnvironment").ProjectEnvironment;
export const ProjectEnvironment: typeof import("./projectEnvironment").ProjectEnvironment = null as any;
utilities.lazyLoad(exports, ["ProjectEnvironment"], () => require("./projectEnvironment"));

export { ProjectGroupArgs, ProjectGroupState } from "./projectGroup";
export type ProjectGroup = import("./projectGroup").ProjectGroup;
export const ProjectGroup: typeof import("./projectGroup").ProjectGroup = null as any;
utilities.lazyLoad(exports, ["ProjectGroup"], () => require("./projectGroup"));

export { ProjectIdentityArgs, ProjectIdentityState } from "./projectIdentity";
export type ProjectIdentity = import("./projectIdentity").ProjectIdentity;
export const ProjectIdentity: typeof import("./projectIdentity").ProjectIdentity = null as any;
utilities.lazyLoad(exports, ["ProjectIdentity"], () => require("./projectIdentity"));

export { ProjectIdentitySpecificPrivilegeArgs, ProjectIdentitySpecificPrivilegeState } from "./projectIdentitySpecificPrivilege";
export type ProjectIdentitySpecificPrivilege = import("./projectIdentitySpecificPrivilege").ProjectIdentitySpecificPrivilege;
export const ProjectIdentitySpecificPrivilege: typeof import("./projectIdentitySpecificPrivilege").ProjectIdentitySpecificPrivilege = null as any;
utilities.lazyLoad(exports, ["ProjectIdentitySpecificPrivilege"], () => require("./projectIdentitySpecificPrivilege"));

export { ProjectRoleArgs, ProjectRoleState } from "./projectRole";
export type ProjectRole = import("./projectRole").ProjectRole;
export const ProjectRole: typeof import("./projectRole").ProjectRole = null as any;
utilities.lazyLoad(exports, ["ProjectRole"], () => require("./projectRole"));

export { ProjectTemplateArgs, ProjectTemplateState } from "./projectTemplate";
export type ProjectTemplate = import("./projectTemplate").ProjectTemplate;
export const ProjectTemplate: typeof import("./projectTemplate").ProjectTemplate = null as any;
utilities.lazyLoad(exports, ["ProjectTemplate"], () => require("./projectTemplate"));

export { ProjectUserArgs, ProjectUserState } from "./projectUser";
export type ProjectUser = import("./projectUser").ProjectUser;
export const ProjectUser: typeof import("./projectUser").ProjectUser = null as any;
utilities.lazyLoad(exports, ["ProjectUser"], () => require("./projectUser"));

export * from "./provider";
import { Provider } from "./provider";

export { SecretArgs, SecretState } from "./secret";
export type Secret = import("./secret").Secret;
export const Secret: typeof import("./secret").Secret = null as any;
utilities.lazyLoad(exports, ["Secret"], () => require("./secret"));

export { SecretApprovalPolicyArgs, SecretApprovalPolicyState } from "./secretApprovalPolicy";
export type SecretApprovalPolicy = import("./secretApprovalPolicy").SecretApprovalPolicy;
export const SecretApprovalPolicy: typeof import("./secretApprovalPolicy").SecretApprovalPolicy = null as any;
utilities.lazyLoad(exports, ["SecretApprovalPolicy"], () => require("./secretApprovalPolicy"));

export { SecretFolderArgs, SecretFolderState } from "./secretFolder";
export type SecretFolder = import("./secretFolder").SecretFolder;
export const SecretFolder: typeof import("./secretFolder").SecretFolder = null as any;
utilities.lazyLoad(exports, ["SecretFolder"], () => require("./secretFolder"));

export { SecretImportArgs, SecretImportState } from "./secretImport";
export type SecretImport = import("./secretImport").SecretImport;
export const SecretImport: typeof import("./secretImport").SecretImport = null as any;
utilities.lazyLoad(exports, ["SecretImport"], () => require("./secretImport"));

export { SecretRotationAwsIamUserSecretArgs, SecretRotationAwsIamUserSecretState } from "./secretRotationAwsIamUserSecret";
export type SecretRotationAwsIamUserSecret = import("./secretRotationAwsIamUserSecret").SecretRotationAwsIamUserSecret;
export const SecretRotationAwsIamUserSecret: typeof import("./secretRotationAwsIamUserSecret").SecretRotationAwsIamUserSecret = null as any;
utilities.lazyLoad(exports, ["SecretRotationAwsIamUserSecret"], () => require("./secretRotationAwsIamUserSecret"));

export { SecretRotationAzureClientSecretArgs, SecretRotationAzureClientSecretState } from "./secretRotationAzureClientSecret";
export type SecretRotationAzureClientSecret = import("./secretRotationAzureClientSecret").SecretRotationAzureClientSecret;
export const SecretRotationAzureClientSecret: typeof import("./secretRotationAzureClientSecret").SecretRotationAzureClientSecret = null as any;
utilities.lazyLoad(exports, ["SecretRotationAzureClientSecret"], () => require("./secretRotationAzureClientSecret"));

export { SecretRotationLdapPasswordArgs, SecretRotationLdapPasswordState } from "./secretRotationLdapPassword";
export type SecretRotationLdapPassword = import("./secretRotationLdapPassword").SecretRotationLdapPassword;
export const SecretRotationLdapPassword: typeof import("./secretRotationLdapPassword").SecretRotationLdapPassword = null as any;
utilities.lazyLoad(exports, ["SecretRotationLdapPassword"], () => require("./secretRotationLdapPassword"));

export { SecretRotationMssqlCredentialsArgs, SecretRotationMssqlCredentialsState } from "./secretRotationMssqlCredentials";
export type SecretRotationMssqlCredentials = import("./secretRotationMssqlCredentials").SecretRotationMssqlCredentials;
export const SecretRotationMssqlCredentials: typeof import("./secretRotationMssqlCredentials").SecretRotationMssqlCredentials = null as any;
utilities.lazyLoad(exports, ["SecretRotationMssqlCredentials"], () => require("./secretRotationMssqlCredentials"));

export { SecretRotationMysqlCredentialsArgs, SecretRotationMysqlCredentialsState } from "./secretRotationMysqlCredentials";
export type SecretRotationMysqlCredentials = import("./secretRotationMysqlCredentials").SecretRotationMysqlCredentials;
export const SecretRotationMysqlCredentials: typeof import("./secretRotationMysqlCredentials").SecretRotationMysqlCredentials = null as any;
utilities.lazyLoad(exports, ["SecretRotationMysqlCredentials"], () => require("./secretRotationMysqlCredentials"));

export { SecretRotationOracledbCredentialsArgs, SecretRotationOracledbCredentialsState } from "./secretRotationOracledbCredentials";
export type SecretRotationOracledbCredentials = import("./secretRotationOracledbCredentials").SecretRotationOracledbCredentials;
export const SecretRotationOracledbCredentials: typeof import("./secretRotationOracledbCredentials").SecretRotationOracledbCredentials = null as any;
utilities.lazyLoad(exports, ["SecretRotationOracledbCredentials"], () => require("./secretRotationOracledbCredentials"));

export { SecretRotationPostgresCredentialsArgs, SecretRotationPostgresCredentialsState } from "./secretRotationPostgresCredentials";
export type SecretRotationPostgresCredentials = import("./secretRotationPostgresCredentials").SecretRotationPostgresCredentials;
export const SecretRotationPostgresCredentials: typeof import("./secretRotationPostgresCredentials").SecretRotationPostgresCredentials = null as any;
utilities.lazyLoad(exports, ["SecretRotationPostgresCredentials"], () => require("./secretRotationPostgresCredentials"));

export { SecretSync1passwordArgs, SecretSync1passwordState } from "./secretSync1password";
export type SecretSync1password = import("./secretSync1password").SecretSync1password;
export const SecretSync1password: typeof import("./secretSync1password").SecretSync1password = null as any;
utilities.lazyLoad(exports, ["SecretSync1password"], () => require("./secretSync1password"));

export { SecretSyncAwsParameterStoreArgs, SecretSyncAwsParameterStoreState } from "./secretSyncAwsParameterStore";
export type SecretSyncAwsParameterStore = import("./secretSyncAwsParameterStore").SecretSyncAwsParameterStore;
export const SecretSyncAwsParameterStore: typeof import("./secretSyncAwsParameterStore").SecretSyncAwsParameterStore = null as any;
utilities.lazyLoad(exports, ["SecretSyncAwsParameterStore"], () => require("./secretSyncAwsParameterStore"));

export { SecretSyncAwsSecretsManagerArgs, SecretSyncAwsSecretsManagerState } from "./secretSyncAwsSecretsManager";
export type SecretSyncAwsSecretsManager = import("./secretSyncAwsSecretsManager").SecretSyncAwsSecretsManager;
export const SecretSyncAwsSecretsManager: typeof import("./secretSyncAwsSecretsManager").SecretSyncAwsSecretsManager = null as any;
utilities.lazyLoad(exports, ["SecretSyncAwsSecretsManager"], () => require("./secretSyncAwsSecretsManager"));

export { SecretSyncAzureAppConfigurationArgs, SecretSyncAzureAppConfigurationState } from "./secretSyncAzureAppConfiguration";
export type SecretSyncAzureAppConfiguration = import("./secretSyncAzureAppConfiguration").SecretSyncAzureAppConfiguration;
export const SecretSyncAzureAppConfiguration: typeof import("./secretSyncAzureAppConfiguration").SecretSyncAzureAppConfiguration = null as any;
utilities.lazyLoad(exports, ["SecretSyncAzureAppConfiguration"], () => require("./secretSyncAzureAppConfiguration"));

export { SecretSyncAzureDevopsArgs, SecretSyncAzureDevopsState } from "./secretSyncAzureDevops";
export type SecretSyncAzureDevops = import("./secretSyncAzureDevops").SecretSyncAzureDevops;
export const SecretSyncAzureDevops: typeof import("./secretSyncAzureDevops").SecretSyncAzureDevops = null as any;
utilities.lazyLoad(exports, ["SecretSyncAzureDevops"], () => require("./secretSyncAzureDevops"));

export { SecretSyncAzureKeyVaultArgs, SecretSyncAzureKeyVaultState } from "./secretSyncAzureKeyVault";
export type SecretSyncAzureKeyVault = import("./secretSyncAzureKeyVault").SecretSyncAzureKeyVault;
export const SecretSyncAzureKeyVault: typeof import("./secretSyncAzureKeyVault").SecretSyncAzureKeyVault = null as any;
utilities.lazyLoad(exports, ["SecretSyncAzureKeyVault"], () => require("./secretSyncAzureKeyVault"));

export { SecretSyncBitbucketArgs, SecretSyncBitbucketState } from "./secretSyncBitbucket";
export type SecretSyncBitbucket = import("./secretSyncBitbucket").SecretSyncBitbucket;
export const SecretSyncBitbucket: typeof import("./secretSyncBitbucket").SecretSyncBitbucket = null as any;
utilities.lazyLoad(exports, ["SecretSyncBitbucket"], () => require("./secretSyncBitbucket"));

export { SecretSyncCloudflarePagesArgs, SecretSyncCloudflarePagesState } from "./secretSyncCloudflarePages";
export type SecretSyncCloudflarePages = import("./secretSyncCloudflarePages").SecretSyncCloudflarePages;
export const SecretSyncCloudflarePages: typeof import("./secretSyncCloudflarePages").SecretSyncCloudflarePages = null as any;
utilities.lazyLoad(exports, ["SecretSyncCloudflarePages"], () => require("./secretSyncCloudflarePages"));

export { SecretSyncCloudflareWorkersArgs, SecretSyncCloudflareWorkersState } from "./secretSyncCloudflareWorkers";
export type SecretSyncCloudflareWorkers = import("./secretSyncCloudflareWorkers").SecretSyncCloudflareWorkers;
export const SecretSyncCloudflareWorkers: typeof import("./secretSyncCloudflareWorkers").SecretSyncCloudflareWorkers = null as any;
utilities.lazyLoad(exports, ["SecretSyncCloudflareWorkers"], () => require("./secretSyncCloudflareWorkers"));

export { SecretSyncDatabricksArgs, SecretSyncDatabricksState } from "./secretSyncDatabricks";
export type SecretSyncDatabricks = import("./secretSyncDatabricks").SecretSyncDatabricks;
export const SecretSyncDatabricks: typeof import("./secretSyncDatabricks").SecretSyncDatabricks = null as any;
utilities.lazyLoad(exports, ["SecretSyncDatabricks"], () => require("./secretSyncDatabricks"));

export { SecretSyncFlyioArgs, SecretSyncFlyioState } from "./secretSyncFlyio";
export type SecretSyncFlyio = import("./secretSyncFlyio").SecretSyncFlyio;
export const SecretSyncFlyio: typeof import("./secretSyncFlyio").SecretSyncFlyio = null as any;
utilities.lazyLoad(exports, ["SecretSyncFlyio"], () => require("./secretSyncFlyio"));

export { SecretSyncGcpSecretManagerArgs, SecretSyncGcpSecretManagerState } from "./secretSyncGcpSecretManager";
export type SecretSyncGcpSecretManager = import("./secretSyncGcpSecretManager").SecretSyncGcpSecretManager;
export const SecretSyncGcpSecretManager: typeof import("./secretSyncGcpSecretManager").SecretSyncGcpSecretManager = null as any;
utilities.lazyLoad(exports, ["SecretSyncGcpSecretManager"], () => require("./secretSyncGcpSecretManager"));

export { SecretSyncGithubArgs, SecretSyncGithubState } from "./secretSyncGithub";
export type SecretSyncGithub = import("./secretSyncGithub").SecretSyncGithub;
export const SecretSyncGithub: typeof import("./secretSyncGithub").SecretSyncGithub = null as any;
utilities.lazyLoad(exports, ["SecretSyncGithub"], () => require("./secretSyncGithub"));

export { SecretSyncGitlabArgs, SecretSyncGitlabState } from "./secretSyncGitlab";
export type SecretSyncGitlab = import("./secretSyncGitlab").SecretSyncGitlab;
export const SecretSyncGitlab: typeof import("./secretSyncGitlab").SecretSyncGitlab = null as any;
utilities.lazyLoad(exports, ["SecretSyncGitlab"], () => require("./secretSyncGitlab"));

export { SecretSyncRenderArgs, SecretSyncRenderState } from "./secretSyncRender";
export type SecretSyncRender = import("./secretSyncRender").SecretSyncRender;
export const SecretSyncRender: typeof import("./secretSyncRender").SecretSyncRender = null as any;
utilities.lazyLoad(exports, ["SecretSyncRender"], () => require("./secretSyncRender"));

export { SecretSyncSupabaseArgs, SecretSyncSupabaseState } from "./secretSyncSupabase";
export type SecretSyncSupabase = import("./secretSyncSupabase").SecretSyncSupabase;
export const SecretSyncSupabase: typeof import("./secretSyncSupabase").SecretSyncSupabase = null as any;
utilities.lazyLoad(exports, ["SecretSyncSupabase"], () => require("./secretSyncSupabase"));

export { SecretTagArgs, SecretTagState } from "./secretTag";
export type SecretTag = import("./secretTag").SecretTag;
export const SecretTag: typeof import("./secretTag").SecretTag = null as any;
utilities.lazyLoad(exports, ["SecretTag"], () => require("./secretTag"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "infisical:index/accessApprovalPolicy:AccessApprovalPolicy":
                return new AccessApprovalPolicy(name, <any>undefined, { urn })
            case "infisical:index/appConnection1password:AppConnection1password":
                return new AppConnection1password(name, <any>undefined, { urn })
            case "infisical:index/appConnectionAws:AppConnectionAws":
                return new AppConnectionAws(name, <any>undefined, { urn })
            case "infisical:index/appConnectionAzureClientSecrets:AppConnectionAzureClientSecrets":
                return new AppConnectionAzureClientSecrets(name, <any>undefined, { urn })
            case "infisical:index/appConnectionBitbucket:AppConnectionBitbucket":
                return new AppConnectionBitbucket(name, <any>undefined, { urn })
            case "infisical:index/appConnectionCloudflare:AppConnectionCloudflare":
                return new AppConnectionCloudflare(name, <any>undefined, { urn })
            case "infisical:index/appConnectionDatabricks:AppConnectionDatabricks":
                return new AppConnectionDatabricks(name, <any>undefined, { urn })
            case "infisical:index/appConnectionFlyio:AppConnectionFlyio":
                return new AppConnectionFlyio(name, <any>undefined, { urn })
            case "infisical:index/appConnectionGcp:AppConnectionGcp":
                return new AppConnectionGcp(name, <any>undefined, { urn })
            case "infisical:index/appConnectionGitlab:AppConnectionGitlab":
                return new AppConnectionGitlab(name, <any>undefined, { urn })
            case "infisical:index/appConnectionLdap:AppConnectionLdap":
                return new AppConnectionLdap(name, <any>undefined, { urn })
            case "infisical:index/appConnectionMssql:AppConnectionMssql":
                return new AppConnectionMssql(name, <any>undefined, { urn })
            case "infisical:index/appConnectionMysql:AppConnectionMysql":
                return new AppConnectionMysql(name, <any>undefined, { urn })
            case "infisical:index/appConnectionOracledb:AppConnectionOracledb":
                return new AppConnectionOracledb(name, <any>undefined, { urn })
            case "infisical:index/appConnectionPostgres:AppConnectionPostgres":
                return new AppConnectionPostgres(name, <any>undefined, { urn })
            case "infisical:index/appConnectionRender:AppConnectionRender":
                return new AppConnectionRender(name, <any>undefined, { urn })
            case "infisical:index/appConnectionSupabase:AppConnectionSupabase":
                return new AppConnectionSupabase(name, <any>undefined, { urn })
            case "infisical:index/dynamicSecretAwsIam:DynamicSecretAwsIam":
                return new DynamicSecretAwsIam(name, <any>undefined, { urn })
            case "infisical:index/dynamicSecretKubernetes:DynamicSecretKubernetes":
                return new DynamicSecretKubernetes(name, <any>undefined, { urn })
            case "infisical:index/dynamicSecretSqlDatabase:DynamicSecretSqlDatabase":
                return new DynamicSecretSqlDatabase(name, <any>undefined, { urn })
            case "infisical:index/group:Group":
                return new Group(name, <any>undefined, { urn })
            case "infisical:index/identity:Identity":
                return new Identity(name, <any>undefined, { urn })
            case "infisical:index/identityAwsAuth:IdentityAwsAuth":
                return new IdentityAwsAuth(name, <any>undefined, { urn })
            case "infisical:index/identityAzureAuth:IdentityAzureAuth":
                return new IdentityAzureAuth(name, <any>undefined, { urn })
            case "infisical:index/identityGcpAuth:IdentityGcpAuth":
                return new IdentityGcpAuth(name, <any>undefined, { urn })
            case "infisical:index/identityKubernetesAuth:IdentityKubernetesAuth":
                return new IdentityKubernetesAuth(name, <any>undefined, { urn })
            case "infisical:index/identityOidcAuth:IdentityOidcAuth":
                return new IdentityOidcAuth(name, <any>undefined, { urn })
            case "infisical:index/identityUniversalAuth:IdentityUniversalAuth":
                return new IdentityUniversalAuth(name, <any>undefined, { urn })
            case "infisical:index/identityUniversalAuthClientSecret:IdentityUniversalAuthClientSecret":
                return new IdentityUniversalAuthClientSecret(name, <any>undefined, { urn })
            case "infisical:index/integrationAwsParameterStore:IntegrationAwsParameterStore":
                return new IntegrationAwsParameterStore(name, <any>undefined, { urn })
            case "infisical:index/integrationAwsSecretsManager:IntegrationAwsSecretsManager":
                return new IntegrationAwsSecretsManager(name, <any>undefined, { urn })
            case "infisical:index/integrationCircleci:IntegrationCircleci":
                return new IntegrationCircleci(name, <any>undefined, { urn })
            case "infisical:index/integrationDatabricks:IntegrationDatabricks":
                return new IntegrationDatabricks(name, <any>undefined, { urn })
            case "infisical:index/integrationGcpSecretManager:IntegrationGcpSecretManager":
                return new IntegrationGcpSecretManager(name, <any>undefined, { urn })
            case "infisical:index/project:Project":
                return new Project(name, <any>undefined, { urn })
            case "infisical:index/projectEnvironment:ProjectEnvironment":
                return new ProjectEnvironment(name, <any>undefined, { urn })
            case "infisical:index/projectGroup:ProjectGroup":
                return new ProjectGroup(name, <any>undefined, { urn })
            case "infisical:index/projectIdentity:ProjectIdentity":
                return new ProjectIdentity(name, <any>undefined, { urn })
            case "infisical:index/projectIdentitySpecificPrivilege:ProjectIdentitySpecificPrivilege":
                return new ProjectIdentitySpecificPrivilege(name, <any>undefined, { urn })
            case "infisical:index/projectRole:ProjectRole":
                return new ProjectRole(name, <any>undefined, { urn })
            case "infisical:index/projectTemplate:ProjectTemplate":
                return new ProjectTemplate(name, <any>undefined, { urn })
            case "infisical:index/projectUser:ProjectUser":
                return new ProjectUser(name, <any>undefined, { urn })
            case "infisical:index/secret:Secret":
                return new Secret(name, <any>undefined, { urn })
            case "infisical:index/secretApprovalPolicy:SecretApprovalPolicy":
                return new SecretApprovalPolicy(name, <any>undefined, { urn })
            case "infisical:index/secretFolder:SecretFolder":
                return new SecretFolder(name, <any>undefined, { urn })
            case "infisical:index/secretImport:SecretImport":
                return new SecretImport(name, <any>undefined, { urn })
            case "infisical:index/secretRotationAwsIamUserSecret:SecretRotationAwsIamUserSecret":
                return new SecretRotationAwsIamUserSecret(name, <any>undefined, { urn })
            case "infisical:index/secretRotationAzureClientSecret:SecretRotationAzureClientSecret":
                return new SecretRotationAzureClientSecret(name, <any>undefined, { urn })
            case "infisical:index/secretRotationLdapPassword:SecretRotationLdapPassword":
                return new SecretRotationLdapPassword(name, <any>undefined, { urn })
            case "infisical:index/secretRotationMssqlCredentials:SecretRotationMssqlCredentials":
                return new SecretRotationMssqlCredentials(name, <any>undefined, { urn })
            case "infisical:index/secretRotationMysqlCredentials:SecretRotationMysqlCredentials":
                return new SecretRotationMysqlCredentials(name, <any>undefined, { urn })
            case "infisical:index/secretRotationOracledbCredentials:SecretRotationOracledbCredentials":
                return new SecretRotationOracledbCredentials(name, <any>undefined, { urn })
            case "infisical:index/secretRotationPostgresCredentials:SecretRotationPostgresCredentials":
                return new SecretRotationPostgresCredentials(name, <any>undefined, { urn })
            case "infisical:index/secretSync1password:SecretSync1password":
                return new SecretSync1password(name, <any>undefined, { urn })
            case "infisical:index/secretSyncAwsParameterStore:SecretSyncAwsParameterStore":
                return new SecretSyncAwsParameterStore(name, <any>undefined, { urn })
            case "infisical:index/secretSyncAwsSecretsManager:SecretSyncAwsSecretsManager":
                return new SecretSyncAwsSecretsManager(name, <any>undefined, { urn })
            case "infisical:index/secretSyncAzureAppConfiguration:SecretSyncAzureAppConfiguration":
                return new SecretSyncAzureAppConfiguration(name, <any>undefined, { urn })
            case "infisical:index/secretSyncAzureDevops:SecretSyncAzureDevops":
                return new SecretSyncAzureDevops(name, <any>undefined, { urn })
            case "infisical:index/secretSyncAzureKeyVault:SecretSyncAzureKeyVault":
                return new SecretSyncAzureKeyVault(name, <any>undefined, { urn })
            case "infisical:index/secretSyncBitbucket:SecretSyncBitbucket":
                return new SecretSyncBitbucket(name, <any>undefined, { urn })
            case "infisical:index/secretSyncCloudflarePages:SecretSyncCloudflarePages":
                return new SecretSyncCloudflarePages(name, <any>undefined, { urn })
            case "infisical:index/secretSyncCloudflareWorkers:SecretSyncCloudflareWorkers":
                return new SecretSyncCloudflareWorkers(name, <any>undefined, { urn })
            case "infisical:index/secretSyncDatabricks:SecretSyncDatabricks":
                return new SecretSyncDatabricks(name, <any>undefined, { urn })
            case "infisical:index/secretSyncFlyio:SecretSyncFlyio":
                return new SecretSyncFlyio(name, <any>undefined, { urn })
            case "infisical:index/secretSyncGcpSecretManager:SecretSyncGcpSecretManager":
                return new SecretSyncGcpSecretManager(name, <any>undefined, { urn })
            case "infisical:index/secretSyncGithub:SecretSyncGithub":
                return new SecretSyncGithub(name, <any>undefined, { urn })
            case "infisical:index/secretSyncGitlab:SecretSyncGitlab":
                return new SecretSyncGitlab(name, <any>undefined, { urn })
            case "infisical:index/secretSyncRender:SecretSyncRender":
                return new SecretSyncRender(name, <any>undefined, { urn })
            case "infisical:index/secretSyncSupabase:SecretSyncSupabase":
                return new SecretSyncSupabase(name, <any>undefined, { urn })
            case "infisical:index/secretTag:SecretTag":
                return new SecretTag(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("infisical", "index/accessApprovalPolicy", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnection1password", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionAws", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionAzureClientSecrets", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionBitbucket", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionCloudflare", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionDatabricks", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionFlyio", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionGcp", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionGitlab", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionLdap", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionMssql", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionMysql", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionOracledb", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionPostgres", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionRender", _module)
pulumi.runtime.registerResourceModule("infisical", "index/appConnectionSupabase", _module)
pulumi.runtime.registerResourceModule("infisical", "index/dynamicSecretAwsIam", _module)
pulumi.runtime.registerResourceModule("infisical", "index/dynamicSecretKubernetes", _module)
pulumi.runtime.registerResourceModule("infisical", "index/dynamicSecretSqlDatabase", _module)
pulumi.runtime.registerResourceModule("infisical", "index/group", _module)
pulumi.runtime.registerResourceModule("infisical", "index/identity", _module)
pulumi.runtime.registerResourceModule("infisical", "index/identityAwsAuth", _module)
pulumi.runtime.registerResourceModule("infisical", "index/identityAzureAuth", _module)
pulumi.runtime.registerResourceModule("infisical", "index/identityGcpAuth", _module)
pulumi.runtime.registerResourceModule("infisical", "index/identityKubernetesAuth", _module)
pulumi.runtime.registerResourceModule("infisical", "index/identityOidcAuth", _module)
pulumi.runtime.registerResourceModule("infisical", "index/identityUniversalAuth", _module)
pulumi.runtime.registerResourceModule("infisical", "index/identityUniversalAuthClientSecret", _module)
pulumi.runtime.registerResourceModule("infisical", "index/integrationAwsParameterStore", _module)
pulumi.runtime.registerResourceModule("infisical", "index/integrationAwsSecretsManager", _module)
pulumi.runtime.registerResourceModule("infisical", "index/integrationCircleci", _module)
pulumi.runtime.registerResourceModule("infisical", "index/integrationDatabricks", _module)
pulumi.runtime.registerResourceModule("infisical", "index/integrationGcpSecretManager", _module)
pulumi.runtime.registerResourceModule("infisical", "index/project", _module)
pulumi.runtime.registerResourceModule("infisical", "index/projectEnvironment", _module)
pulumi.runtime.registerResourceModule("infisical", "index/projectGroup", _module)
pulumi.runtime.registerResourceModule("infisical", "index/projectIdentity", _module)
pulumi.runtime.registerResourceModule("infisical", "index/projectIdentitySpecificPrivilege", _module)
pulumi.runtime.registerResourceModule("infisical", "index/projectRole", _module)
pulumi.runtime.registerResourceModule("infisical", "index/projectTemplate", _module)
pulumi.runtime.registerResourceModule("infisical", "index/projectUser", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secret", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretApprovalPolicy", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretFolder", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretImport", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretRotationAwsIamUserSecret", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretRotationAzureClientSecret", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretRotationLdapPassword", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretRotationMssqlCredentials", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretRotationMysqlCredentials", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretRotationOracledbCredentials", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretRotationPostgresCredentials", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSync1password", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncAwsParameterStore", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncAwsSecretsManager", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncAzureAppConfiguration", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncAzureDevops", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncAzureKeyVault", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncBitbucket", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncCloudflarePages", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncCloudflareWorkers", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncDatabricks", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncFlyio", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncGcpSecretManager", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncGithub", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncGitlab", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncRender", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretSyncSupabase", _module)
pulumi.runtime.registerResourceModule("infisical", "index/secretTag", _module)
pulumi.runtime.registerResourcePackage("infisical", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:infisical") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
