// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ProjectIdentityProvisioning extends pulumi.CustomResource {
    /**
     * Get an existing ProjectIdentityProvisioning resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectIdentityProvisioningState, opts?: pulumi.CustomResourceOptions): ProjectIdentityProvisioning {
        return new ProjectIdentityProvisioning(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/projectIdentityProvisioning:ProjectIdentityProvisioning';

    /**
     * Returns true if the given object is an instance of ProjectIdentityProvisioning.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectIdentityProvisioning {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectIdentityProvisioning.__pulumiType;
    }

    /**
     * The authentication methods configured for the identity.
     */
    declare public /*out*/ readonly authMethods: pulumi.Output<string[]>;
    /**
     * Whether the identity has delete protection enabled. Defaults to false.
     */
    declare public readonly hasDeleteProtection: pulumi.Output<boolean>;
    /**
     * The metadata associated with this identity.
     */
    declare public readonly metadatas: pulumi.Output<outputs.ProjectIdentityProvisioningMetadata[] | undefined>;
    /**
     * The name of the identity.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the project that owns this identity.
     */
    declare public readonly projectId: pulumi.Output<string>;

    /**
     * Create a ProjectIdentityProvisioning resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectIdentityProvisioningArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectIdentityProvisioningArgs | ProjectIdentityProvisioningState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectIdentityProvisioningState | undefined;
            resourceInputs["authMethods"] = state?.authMethods;
            resourceInputs["hasDeleteProtection"] = state?.hasDeleteProtection;
            resourceInputs["metadatas"] = state?.metadatas;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
        } else {
            const args = argsOrState as ProjectIdentityProvisioningArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["hasDeleteProtection"] = args?.hasDeleteProtection;
            resourceInputs["metadatas"] = args?.metadatas;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["authMethods"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectIdentityProvisioning.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProjectIdentityProvisioning resources.
 */
export interface ProjectIdentityProvisioningState {
    /**
     * The authentication methods configured for the identity.
     */
    authMethods?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether the identity has delete protection enabled. Defaults to false.
     */
    hasDeleteProtection?: pulumi.Input<boolean>;
    /**
     * The metadata associated with this identity.
     */
    metadatas?: pulumi.Input<pulumi.Input<inputs.ProjectIdentityProvisioningMetadata>[]>;
    /**
     * The name of the identity.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the project that owns this identity.
     */
    projectId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ProjectIdentityProvisioning resource.
 */
export interface ProjectIdentityProvisioningArgs {
    /**
     * Whether the identity has delete protection enabled. Defaults to false.
     */
    hasDeleteProtection?: pulumi.Input<boolean>;
    /**
     * The metadata associated with this identity.
     */
    metadatas?: pulumi.Input<pulumi.Input<inputs.ProjectIdentityProvisioningMetadata>[]>;
    /**
     * The name of the identity.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the project that owns this identity.
     */
    projectId: pulumi.Input<string>;
}
