// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SecretRotationOracledbCredentials extends pulumi.CustomResource {
    /**
     * Get an existing SecretRotationOracledbCredentials resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretRotationOracledbCredentialsState, opts?: pulumi.CustomResourceOptions): SecretRotationOracledbCredentials {
        return new SecretRotationOracledbCredentials(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/secretRotationOracledbCredentials:SecretRotationOracledbCredentials';

    /**
     * Returns true if the given object is an instance of SecretRotationOracledbCredentials.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretRotationOracledbCredentials {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretRotationOracledbCredentials.__pulumiType;
    }

    /**
     * Whether secrets should be automatically rotated.
     */
    declare public readonly autoRotationEnabled: pulumi.Output<boolean>;
    /**
     * The ID of the connection to use for the secret rotation.
     */
    declare public readonly connectionId: pulumi.Output<string>;
    /**
     * The description of the secret rotation.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The slug of the project environment to rotate secrets from.
     */
    declare public readonly environment: pulumi.Output<string>;
    /**
     * The name of the secret rotation.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Parameters to modify how secrets are rotated.
     */
    declare public readonly parameters: pulumi.Output<outputs.SecretRotationOracledbCredentialsParameters>;
    /**
     * The ID of the Infisical project to create the secret rotation in.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * At which UTC time the rotation should occur.
     */
    declare public readonly rotateAtUtc: pulumi.Output<outputs.SecretRotationOracledbCredentialsRotateAtUtc>;
    /**
     * How many days to wait between each rotation.
     */
    declare public readonly rotationInterval: pulumi.Output<number>;
    /**
     * The folder path to rotate secrets from.
     */
    declare public readonly secretPath: pulumi.Output<string>;
    /**
     * Secret mappings to modify how secrets are rotated.
     */
    declare public readonly secretsMapping: pulumi.Output<outputs.SecretRotationOracledbCredentialsSecretsMapping>;
    /**
     * Temporary parameters to modify how secrets are rotated.
     */
    declare public readonly temporaryParameters: pulumi.Output<outputs.SecretRotationOracledbCredentialsTemporaryParameters | undefined>;

    /**
     * Create a SecretRotationOracledbCredentials resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretRotationOracledbCredentialsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretRotationOracledbCredentialsArgs | SecretRotationOracledbCredentialsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretRotationOracledbCredentialsState | undefined;
            resourceInputs["autoRotationEnabled"] = state?.autoRotationEnabled;
            resourceInputs["connectionId"] = state?.connectionId;
            resourceInputs["description"] = state?.description;
            resourceInputs["environment"] = state?.environment;
            resourceInputs["name"] = state?.name;
            resourceInputs["parameters"] = state?.parameters;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["rotateAtUtc"] = state?.rotateAtUtc;
            resourceInputs["rotationInterval"] = state?.rotationInterval;
            resourceInputs["secretPath"] = state?.secretPath;
            resourceInputs["secretsMapping"] = state?.secretsMapping;
            resourceInputs["temporaryParameters"] = state?.temporaryParameters;
        } else {
            const args = argsOrState as SecretRotationOracledbCredentialsArgs | undefined;
            if (args?.connectionId === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectionId'");
            }
            if (args?.environment === undefined && !opts.urn) {
                throw new Error("Missing required property 'environment'");
            }
            if (args?.parameters === undefined && !opts.urn) {
                throw new Error("Missing required property 'parameters'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.secretPath === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretPath'");
            }
            if (args?.secretsMapping === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretsMapping'");
            }
            resourceInputs["autoRotationEnabled"] = args?.autoRotationEnabled;
            resourceInputs["connectionId"] = args?.connectionId;
            resourceInputs["description"] = args?.description;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["name"] = args?.name;
            resourceInputs["parameters"] = args?.parameters;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["rotateAtUtc"] = args?.rotateAtUtc;
            resourceInputs["rotationInterval"] = args?.rotationInterval;
            resourceInputs["secretPath"] = args?.secretPath;
            resourceInputs["secretsMapping"] = args?.secretsMapping;
            resourceInputs["temporaryParameters"] = args?.temporaryParameters;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretRotationOracledbCredentials.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SecretRotationOracledbCredentials resources.
 */
export interface SecretRotationOracledbCredentialsState {
    /**
     * Whether secrets should be automatically rotated.
     */
    autoRotationEnabled?: pulumi.Input<boolean>;
    /**
     * The ID of the connection to use for the secret rotation.
     */
    connectionId?: pulumi.Input<string>;
    /**
     * The description of the secret rotation.
     */
    description?: pulumi.Input<string>;
    /**
     * The slug of the project environment to rotate secrets from.
     */
    environment?: pulumi.Input<string>;
    /**
     * The name of the secret rotation.
     */
    name?: pulumi.Input<string>;
    /**
     * Parameters to modify how secrets are rotated.
     */
    parameters?: pulumi.Input<inputs.SecretRotationOracledbCredentialsParameters>;
    /**
     * The ID of the Infisical project to create the secret rotation in.
     */
    projectId?: pulumi.Input<string>;
    /**
     * At which UTC time the rotation should occur.
     */
    rotateAtUtc?: pulumi.Input<inputs.SecretRotationOracledbCredentialsRotateAtUtc>;
    /**
     * How many days to wait between each rotation.
     */
    rotationInterval?: pulumi.Input<number>;
    /**
     * The folder path to rotate secrets from.
     */
    secretPath?: pulumi.Input<string>;
    /**
     * Secret mappings to modify how secrets are rotated.
     */
    secretsMapping?: pulumi.Input<inputs.SecretRotationOracledbCredentialsSecretsMapping>;
    /**
     * Temporary parameters to modify how secrets are rotated.
     */
    temporaryParameters?: pulumi.Input<inputs.SecretRotationOracledbCredentialsTemporaryParameters>;
}

/**
 * The set of arguments for constructing a SecretRotationOracledbCredentials resource.
 */
export interface SecretRotationOracledbCredentialsArgs {
    /**
     * Whether secrets should be automatically rotated.
     */
    autoRotationEnabled?: pulumi.Input<boolean>;
    /**
     * The ID of the connection to use for the secret rotation.
     */
    connectionId: pulumi.Input<string>;
    /**
     * The description of the secret rotation.
     */
    description?: pulumi.Input<string>;
    /**
     * The slug of the project environment to rotate secrets from.
     */
    environment: pulumi.Input<string>;
    /**
     * The name of the secret rotation.
     */
    name?: pulumi.Input<string>;
    /**
     * Parameters to modify how secrets are rotated.
     */
    parameters: pulumi.Input<inputs.SecretRotationOracledbCredentialsParameters>;
    /**
     * The ID of the Infisical project to create the secret rotation in.
     */
    projectId: pulumi.Input<string>;
    /**
     * At which UTC time the rotation should occur.
     */
    rotateAtUtc?: pulumi.Input<inputs.SecretRotationOracledbCredentialsRotateAtUtc>;
    /**
     * How many days to wait between each rotation.
     */
    rotationInterval?: pulumi.Input<number>;
    /**
     * The folder path to rotate secrets from.
     */
    secretPath: pulumi.Input<string>;
    /**
     * Secret mappings to modify how secrets are rotated.
     */
    secretsMapping: pulumi.Input<inputs.SecretRotationOracledbCredentialsSecretsMapping>;
    /**
     * Temporary parameters to modify how secrets are rotated.
     */
    temporaryParameters?: pulumi.Input<inputs.SecretRotationOracledbCredentialsTemporaryParameters>;
}
