// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Webhook extends pulumi.CustomResource {
    /**
     * Get an existing Webhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WebhookState, opts?: pulumi.CustomResourceOptions): Webhook {
        return new Webhook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/webhook:Webhook';

    /**
     * Returns true if the given object is an instance of Webhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Webhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Webhook.__pulumiType;
    }

    /**
     * The slug of the environment the webhook listens to.
     */
    declare public readonly environment: pulumi.Output<string>;
    /**
     * The events that trigger the webhook. Options: secrets.modified, secrets.rotation-failed. An empty set means the webhook fires on every supported event.
     */
    declare public readonly eventsFilters: pulumi.Output<string[]>;
    /**
     * Whether the webhook is disabled. Defaults to false.
     */
    declare public readonly isDisabled: pulumi.Output<boolean>;
    /**
     * The ID of the project the webhook belongs to.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * The secret path the webhook listens to. Defaults to '/'.
     */
    declare public readonly secretPath: pulumi.Output<string>;
    /**
     * The webhook type. Options: general, slack, microsoft-teams. Defaults to 'general'.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * The secret key used to sign the webhook payload so the receiver can verify it. Write-only: it is never returned by the API, so it cannot be imported.
     */
    declare public readonly webhookSecretKey: pulumi.Output<string | undefined>;
    /**
     * The URL Infisical sends the event payload to.
     */
    declare public readonly webhookUrl: pulumi.Output<string>;

    /**
     * Create a Webhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebhookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WebhookArgs | WebhookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WebhookState | undefined;
            resourceInputs["environment"] = state?.environment;
            resourceInputs["eventsFilters"] = state?.eventsFilters;
            resourceInputs["isDisabled"] = state?.isDisabled;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["secretPath"] = state?.secretPath;
            resourceInputs["type"] = state?.type;
            resourceInputs["webhookSecretKey"] = state?.webhookSecretKey;
            resourceInputs["webhookUrl"] = state?.webhookUrl;
        } else {
            const args = argsOrState as WebhookArgs | undefined;
            if (args?.environment === undefined && !opts.urn) {
                throw new Error("Missing required property 'environment'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.webhookUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'webhookUrl'");
            }
            resourceInputs["environment"] = args?.environment;
            resourceInputs["eventsFilters"] = args?.eventsFilters;
            resourceInputs["isDisabled"] = args?.isDisabled;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["secretPath"] = args?.secretPath;
            resourceInputs["type"] = args?.type;
            resourceInputs["webhookSecretKey"] = args?.webhookSecretKey ? pulumi.secret(args.webhookSecretKey) : undefined;
            resourceInputs["webhookUrl"] = args?.webhookUrl ? pulumi.secret(args.webhookUrl) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["webhookSecretKey", "webhookUrl"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Webhook.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Webhook resources.
 */
export interface WebhookState {
    /**
     * The slug of the environment the webhook listens to.
     */
    environment?: pulumi.Input<string | undefined>;
    /**
     * The events that trigger the webhook. Options: secrets.modified, secrets.rotation-failed. An empty set means the webhook fires on every supported event.
     */
    eventsFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the webhook is disabled. Defaults to false.
     */
    isDisabled?: pulumi.Input<boolean | undefined>;
    /**
     * The ID of the project the webhook belongs to.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * The secret path the webhook listens to. Defaults to '/'.
     */
    secretPath?: pulumi.Input<string | undefined>;
    /**
     * The webhook type. Options: general, slack, microsoft-teams. Defaults to 'general'.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * The secret key used to sign the webhook payload so the receiver can verify it. Write-only: it is never returned by the API, so it cannot be imported.
     */
    webhookSecretKey?: pulumi.Input<string | undefined>;
    /**
     * The URL Infisical sends the event payload to.
     */
    webhookUrl?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Webhook resource.
 */
export interface WebhookArgs {
    /**
     * The slug of the environment the webhook listens to.
     */
    environment: pulumi.Input<string>;
    /**
     * The events that trigger the webhook. Options: secrets.modified, secrets.rotation-failed. An empty set means the webhook fires on every supported event.
     */
    eventsFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the webhook is disabled. Defaults to false.
     */
    isDisabled?: pulumi.Input<boolean | undefined>;
    /**
     * The ID of the project the webhook belongs to.
     */
    projectId: pulumi.Input<string>;
    /**
     * The secret path the webhook listens to. Defaults to '/'.
     */
    secretPath?: pulumi.Input<string | undefined>;
    /**
     * The webhook type. Options: general, slack, microsoft-teams. Defaults to 'general'.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * The secret key used to sign the webhook payload so the receiver can verify it. Write-only: it is never returned by the API, so it cannot be imported.
     */
    webhookSecretKey?: pulumi.Input<string | undefined>;
    /**
     * The URL Infisical sends the event payload to.
     */
    webhookUrl: pulumi.Input<string>;
}
