// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class DynamicSecretKubernetesConfigurationStaticConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Kubernetes namespace where the service account exists.
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        /// <summary>
        /// Name of the service account to generate tokens for.
        /// </summary>
        [Input("serviceAccountName", required: true)]
        public Input<string> ServiceAccountName { get; set; } = null!;

        public DynamicSecretKubernetesConfigurationStaticConfigArgs()
        {
        }
        public static new DynamicSecretKubernetesConfigurationStaticConfigArgs Empty => new DynamicSecretKubernetesConfigurationStaticConfigArgs();
    }
}
