// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class IntegrationAwsParameterStoreOptionsAwsTagArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key of the tag.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The value of the tag.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public IntegrationAwsParameterStoreOptionsAwsTagArgs()
        {
        }
        public static new IntegrationAwsParameterStoreOptionsAwsTagArgs Empty => new IntegrationAwsParameterStoreOptionsAwsTagArgs();
    }
}
