// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class IntegrationAwsParameterStoreOptionsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("awsTags")]
        private InputList<Inputs.IntegrationAwsParameterStoreOptionsAwsTagGetArgs>? _awsTags;

        /// <summary>
        /// Tags to attach to the AWS parameter store secrets.
        /// </summary>
        public InputList<Inputs.IntegrationAwsParameterStoreOptionsAwsTagGetArgs> AwsTags
        {
            get => _awsTags ?? (_awsTags = new InputList<Inputs.IntegrationAwsParameterStoreOptionsAwsTagGetArgs>());
            set => _awsTags = value;
        }

        /// <summary>
        /// Whether to disable deletion of existing secrets in AWS Parameter Store.
        /// </summary>
        [Input("shouldDisableDelete")]
        public Input<bool>? ShouldDisableDelete { get; set; }

        public IntegrationAwsParameterStoreOptionsGetArgs()
        {
        }
        public static new IntegrationAwsParameterStoreOptionsGetArgs Empty => new IntegrationAwsParameterStoreOptionsGetArgs();
    }
}
