// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class ProjectTemplateEnvironmentGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the environment
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The position of the environment
        /// </summary>
        [Input("position", required: true)]
        public Input<int> Position { get; set; } = null!;

        /// <summary>
        /// The slug of the environment
        /// </summary>
        [Input("slug", required: true)]
        public Input<string> Slug { get; set; } = null!;

        public ProjectTemplateEnvironmentGetArgs()
        {
        }
        public static new ProjectTemplateEnvironmentGetArgs Empty => new ProjectTemplateEnvironmentGetArgs();
    }
}
