// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretRotationLdapPasswordTemporaryParametersArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The password of the provided principal if 'parameters.rotation_method' is set to 'target-principal'.
        /// </summary>
        [Input("password")]
        public Input<string>? Password { get; set; }

        public SecretRotationLdapPasswordTemporaryParametersArgs()
        {
        }
        public static new SecretRotationLdapPasswordTemporaryParametersArgs Empty => new SecretRotationLdapPasswordTemporaryParametersArgs();
    }
}
