// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretRotationMssqlCredentialsSecretsMappingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the secret that the generated password will be mapped to.
        /// </summary>
        [Input("password", required: true)]
        public Input<string> Password { get; set; } = null!;

        /// <summary>
        /// The name of the secret that the active username will be mapped to.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public SecretRotationMssqlCredentialsSecretsMappingGetArgs()
        {
        }
        public static new SecretRotationMssqlCredentialsSecretsMappingGetArgs Empty => new SecretRotationMssqlCredentialsSecretsMappingGetArgs();
    }
}
