// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretSyncCloudflareWorkersDestinationConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Cloudflare Workers script ID where the secrets will be synced
        /// </summary>
        [Input("scriptId", required: true)]
        public Input<string> ScriptId { get; set; } = null!;

        public SecretSyncCloudflareWorkersDestinationConfigArgs()
        {
        }
        public static new SecretSyncCloudflareWorkersDestinationConfigArgs Empty => new SecretSyncCloudflareWorkersDestinationConfigArgs();
    }
}
