// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretSyncAzureAppConfigurationDestinationConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The URL of your Azure App Configuration
        /// </summary>
        [Input("configurationUrl", required: true)]
        public Input<string> ConfigurationUrl { get; set; } = null!;

        /// <summary>
        /// The label to attach to secrets created in Azure App Configuration
        /// </summary>
        [Input("label")]
        public Input<string>? Label { get; set; }

        public SecretSyncAzureAppConfigurationDestinationConfigArgs()
        {
        }
        public static new SecretSyncAzureAppConfigurationDestinationConfigArgs Empty => new SecretSyncAzureAppConfigurationDestinationConfigArgs();
    }
}
