// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretRotationLdapPasswordParametersPasswordRequirementsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// String of allowed symbols for password generation.
        /// </summary>
        [Input("allowedSymbols")]
        public Input<string>? AllowedSymbols { get; set; }

        /// <summary>
        /// The length of the generated password.
        /// </summary>
        [Input("length", required: true)]
        public Input<int> Length { get; set; } = null!;

        /// <summary>
        /// Required character types in the generated password.
        /// </summary>
        [Input("required", required: true)]
        public Input<Inputs.SecretRotationLdapPasswordParametersPasswordRequirementsRequiredArgs> Required { get; set; } = null!;

        public SecretRotationLdapPasswordParametersPasswordRequirementsArgs()
        {
        }
        public static new SecretRotationLdapPasswordParametersPasswordRequirementsArgs Empty => new SecretRotationLdapPasswordParametersPasswordRequirementsArgs();
    }
}
