// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretApprovalPolicyApproverArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the approver
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The type of approver. Either group or user
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// The username of the approver. By default, this is the email
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public SecretApprovalPolicyApproverArgs()
        {
        }
        public static new SecretApprovalPolicyApproverArgs Empty => new SecretApprovalPolicyApproverArgs();
    }
}
