// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretSyncCloudflarePagesDestinationConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Cloudflare Pages environment (production, preview) where the secrets will be synced
        /// </summary>
        [Input("environment", required: true)]
        public Input<string> Environment { get; set; } = null!;

        /// <summary>
        /// The Cloudflare Pages project name where the secrets will be synced
        /// </summary>
        [Input("projectName", required: true)]
        public Input<string> ProjectName { get; set; } = null!;

        public SecretSyncCloudflarePagesDestinationConfigGetArgs()
        {
        }
        public static new SecretSyncCloudflarePagesDestinationConfigGetArgs Empty => new SecretSyncCloudflarePagesDestinationConfigGetArgs();
    }
}
