// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretRotationLdapPasswordParametersPasswordRequirementsRequiredArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Minimum number of digits required in the password.
        /// </summary>
        [Input("digits", required: true)]
        public Input<int> Digits { get; set; } = null!;

        /// <summary>
        /// Minimum number of lowercase letters required in the password.
        /// </summary>
        [Input("lowercase", required: true)]
        public Input<int> Lowercase { get; set; } = null!;

        /// <summary>
        /// Minimum number of symbols required in the password.
        /// </summary>
        [Input("symbols", required: true)]
        public Input<int> Symbols { get; set; } = null!;

        /// <summary>
        /// Minimum number of uppercase letters required in the password.
        /// </summary>
        [Input("uppercase", required: true)]
        public Input<int> Uppercase { get; set; } = null!;

        public SecretRotationLdapPasswordParametersPasswordRequirementsRequiredArgs()
        {
        }
        public static new SecretRotationLdapPasswordParametersPasswordRequirementsRequiredArgs Empty => new SecretRotationLdapPasswordParametersPasswordRequirementsRequiredArgs();
    }
}
