// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Infisical.Inputs
{

    public sealed class SecretRotationMysqlCredentialsParametersArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The username of the first login to rotate passwords for. This user must already exists in your database.
        /// </summary>
        [Input("username1", required: true)]
        public Input<string> Username1 { get; set; } = null!;

        /// <summary>
        /// The username of the second login to rotate passwords for. This user must already exists in your database.
        /// </summary>
        [Input("username2", required: true)]
        public Input<string> Username2 { get; set; } = null!;

        public SecretRotationMysqlCredentialsParametersArgs()
        {
        }
        public static new SecretRotationMysqlCredentialsParametersArgs Empty => new SecretRotationMysqlCredentialsParametersArgs();
    }
}
