name: release
on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  release-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/actions@v6
        with:
          pulumi-version: dev
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: get version
        id: get_version
        run: echo "version=v$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"
      - name: npm publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
  release-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/actions@v6
        with:
          pulumi-version: dev
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: npm publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ACCESS_TOKEN }}
